// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using WuicCore.Interfaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.OData.ModelBuilder;

namespace WuicCore.Server.Database.Models;

public partial class Person: GenericConfiguration<Person>
{
    public int PersonId { get; set; }

    public string FullName { get; set; }


    public string SearchName { get; set; }

    public bool IsPermittedToLogon { get; set; }

    public string LogonName { get; set; }

    public bool IsExternalLogonProvider { get; set; }

    public byte[] HashedPassword { get; set; }

    public bool IsSystemUser { get; set; }

    public bool IsEmployee { get; set; }

    public bool IsSalesperson { get; set; }

    public string UserPreferences { get; set; }

    public string PhoneNumber { get; set; }

    public string FaxNumber { get; set; }

    public string EmailAddress { get; set; }

    public byte[] Photo { get; set; }

    public string CustomFields { get; set; }

    public string OtherLanguages { get; set; }

    public int LastEditedBy { get; set; }

    public override void SpecialConfigure(EntityTypeBuilder<Person> entity)
    {
        entity.HasKey(e => e.PersonId).HasName("PK_Application_People");

        entity
            .ToTable("People", "Application")
            .ToTable(tb => tb.IsTemporal(ttb =>
            {
                ttb.UseHistoryTable("People_Archive", "Application");
                ttb
                        .HasPeriodStart("ValidFrom")
                        .HasColumnName("ValidFrom");
                ttb
                        .HasPeriodEnd("ValidTo")
                        .HasColumnName("ValidTo");
            }));

        entity.HasIndex(e => e.FullName, "IX_Application_People_FullName");

        entity.HasIndex(e => e.IsEmployee, "IX_Application_People_IsEmployee");

        entity.HasIndex(e => e.IsSalesperson, "IX_Application_People_IsSalesperson");

        entity.HasIndex(e => new { e.IsPermittedToLogon, e.PersonId }, "IX_Application_People_Perf_20160301_05");

        entity.Property(e => e.PersonId)
            .ValueGeneratedNever()
            .HasColumnName("PersonID");
        entity.Property(e => e.EmailAddress).HasMaxLength(256);
        entity.Property(e => e.FaxNumber).HasMaxLength(20);
        entity.Property(e => e.FullName)
            .IsRequired()
            .HasMaxLength(50);
        entity.Property(e => e.LogonName).HasMaxLength(50);
        entity.Property(e => e.PhoneNumber).HasMaxLength(20);
        entity.Property(e => e.SearchName)
            .IsRequired()
            .HasMaxLength(101);
    }
}
