#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Genera Reports/fatture_inviate/Report.mrt — layout Aruba PEC FPR-style.

Sezioni (top-down):
  1. ReportTitleBand:    "FATTURA" + "nr {numero} del {data}" + "Data invio:" right-aligned
  2. HeaderBand:         FORNITORE | CLIENTE in due colonne (light-gray bg)
  3. HeaderBand:         "PRODOTTI E SERVIZI" (titolo centrato + header table)
  4. DataBand on righe:  riga-per-riga (NR, descrizione, qta, prezzo, importo, iva, natura)
  5. HeaderBand:         "METODO DI PAGAMENTO"
  6. DataBand on scadenze: rata, modalita, banca, iban, bic, data, importo
  7. HeaderBand:         "REGIME FISCALE" (causale codice + descrizione)
  8. HeaderBand:         "DATI AGGIUNTIVI" (DATI BOLLO + CAUSALE)
  9. HeaderBand:         "RIEPILOGO IVA | CALCOLO FATTURA" + Netto a pagare
 10. PageFooter:         disclaimer + WUIC logo (rimpiazza Aruba PEC + aruba.it)

Connessione + parametro @fattura_id riusati dalla versione precedente (Report_NEW.mrt).

Output: C:/src/Wuic/FatturazioneElettronica/Reports/fatture_inviate/Report.mrt
"""
import base64
import os
from pathlib import Path
from textwrap import dedent
import xml.etree.ElementTree as ET  # noqa: F401  (kept for future validation)

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORT_DIR = REPO_ROOT / 'Reports' / 'fatture_inviate'
OUTPUT_PATH = REPORT_DIR / 'Report.mrt'
LOGO_PATH = REPORT_DIR / 'wuic-logo.png'

# Connessione cifrata copiata dal Report_NEW.mrt (stessa istanza/DB).
CONN_STRING_ENC = (
    "9HT5KEZKu93iWr346T2k29Fa90hPS3u8YlvlmOrEsU/ccM3ryEvq8eYTzfRkXGEf"
    "2GD7z0dR0/FpTr3JYxikj98a9cLJXUPIRhWhvepU43/VePUJTWjT3eNG2clqJacv"
    "0SDZiU9ZS8hqTP3MYgAlXtwa1UjdWavVclxlzGIA7EbVOPfLRk2jgUVh7dzpEKQP"
    "w1rRCcxKIqRhTf2Y6hTgP8RqzStNTJMZYVzorGcsZX/2cLUJYUtLCX9McdzxBKQP"
    "1RTziU9W8vniQaGcTgiiXg=="
)

# ── SQL: ricco di JOIN per portare tutto cio' che serve al layout ────────
# SQL: tutto su singola riga + spazi normalizzati (Stimulsoft StiSqlSource
# parser fragile su whitespace multipli, originale Report_NEW.mrt era
# tutto su una linea senza padding).
#
# Nota: il SQL e' "custom" (non auto-generato dal framework). Il framework
# riconosce le query auto-generate dalla presenza della colonna sentinella
# `1 AS [__autogenerated]` (iniettata da `_Metadati_methods.fixQueryReport`).
# Le nostre query NON hanno quella sentinella -> vengono preservate come-e'.
_FATT_TBL = "[FatturazioneElettronica_Data].[dbo].[fatture_inviate]"
SQL_FATTURA = " ".join((
    f"SELECT {_FATT_TBL}.[id] AS [id],",
    f"{_FATT_TBL}.[numero] AS [numero],",
    f"{_FATT_TBL}.[serie] AS [serie],",
    f"{_FATT_TBL}.[progressivo] AS [progressivo],",
    f"{_FATT_TBL}.[anno] AS [anno],",
    f"{_FATT_TBL}.[data_documento] AS [data_documento],",
    # FK base columns — required for Stimulsoft lookup binding
    f"{_FATT_TBL}.[cliente_id] AS [cliente_id],",
    f"{_FATT_TBL}.[pagamento_id] AS [pagamento_id],",
    f"{_FATT_TBL}.[banca_id] AS [banca_id],",
    f"{_FATT_TBL}.[causale_id] AS [causale_id],",
    # Mantiene il nome WUIC-convention SOLO per ragione_sociale (gia' lookup
    # registrato dal designer originale). Per gli altri usa alias semplici
    # CLI_X — Stimulsoft li tratta come colonne string plain di fatture_inviate
    # senza tentare lookup-binding (che falliva quando il nome conteneva ___).
    "[cliente_id_clienti].[ragione_sociale] AS [clienti___ragione_sociale__cliente_id],",
    "ISNULL([cliente_id_clienti].[partita_iva],'') AS [cli_piva],",
    "ISNULL([cliente_id_clienti].[codice_fiscale],'') AS [cli_cf],",
    "ISNULL([cliente_id_clienti].[indirizzo],'') AS [cli_indirizzo],",
    "ISNULL([cliente_id_clienti].[cap],'') AS [cli_cap],",
    "ISNULL([cliente_id_clienti].[citta],'') AS [cli_citta],",
    "ISNULL([cliente_id_clienti].[provincia],'') AS [cli_prov],",
    "ISNULL([cliente_id_clienti].[nazione],'IT') AS [cli_naz],",
    "ISNULL([cliente_id_clienti].[codice_destinatario],'') AS [cli_cd],",
    "ISNULL([cliente_id_clienti].[email],'') AS [cli_email],",
    "ISNULL([cliente_id_clienti].[pec],'') AS [cli_pec],",
    "[pagamento_id_pagamenti].[descrizione] AS [pagamenti___descrizione__pagamento_id],",
    "ISNULL([pagamento_id_pagamenti].[codice_sdi], '') AS [pagamenti___codice_sdi__pagamento_id],",
    "[banca_id_banche].[descrizione] AS [banche___descrizione__banca_id],",
    "ISNULL([banca_id_banche].[iban], '') AS [banche___iban__banca_id],",
    "ISNULL([banca_id_banche].[bic_swift], '') AS [banche___bic_swift__banca_id],",
    f"{_FATT_TBL}.[causale] AS [causale],",
    "[causale_id_causali].[descrizione] AS [causali___descrizione__causale_id],",
    f"{_FATT_TBL}.[bollo_valore] AS [bollo_valore],",
    f"{_FATT_TBL}.[imponibile] AS [imponibile],",
    f"{_FATT_TBL}.[iva] AS [iva],",
    f"{_FATT_TBL}.[totale] AS [totale],",
    f"{_FATT_TBL}.[stato] AS [stato],",
    f"{_FATT_TBL}.[stato_sdi] AS [stato_sdi],",
    f"{_FATT_TBL}.[data_creazione] AS [data_invio]",
    f"FROM {_FATT_TBL}",
    f"LEFT JOIN [FatturazioneElettronica_Data].[dbo].[clienti] AS [cliente_id_clienti] ON {_FATT_TBL}.[cliente_id] = [cliente_id_clienti].[id]",
    f"LEFT JOIN [FatturazioneElettronica_Data].[dbo].[pagamenti] AS [pagamento_id_pagamenti] ON {_FATT_TBL}.[pagamento_id] = [pagamento_id_pagamenti].[id]",
    f"LEFT JOIN [FatturazioneElettronica_Data].[dbo].[banche] AS [banca_id_banche] ON {_FATT_TBL}.[banca_id] = [banca_id_banche].[id]",
    f"LEFT JOIN [FatturazioneElettronica_Data].[dbo].[causali] AS [causale_id_causali] ON {_FATT_TBL}.[causale_id] = [causale_id_causali].[id]",
    f"WHERE COALESCE({_FATT_TBL}.[cancellato], 0) = 0 AND {_FATT_TBL}.[id] = @fattura_id",
))

SQL_RIGHE = (
    "SELECT r.[id] AS [id], r.[fattura_id] AS [fattura_id], r.[riga] AS [riga], "
    "r.[descrizione] AS [descrizione], r.[quantita] AS [quantita], "
    "ISNULL(um.[codice], '') AS [um_codice], "
    "r.[prezzo_unitario] AS [prezzo_unitario], r.[sconto_perc] AS [sconto_perc], "
    "r.[imponibile_riga] AS [imponibile_riga], r.[iva_riga] AS [iva_riga], "
    "r.[totale_riga] AS [totale_riga], "
    "ISNULL(ci.[aliquota], 0)  AS [aliquota], "
    "ISNULL(ci.[natura_sdi], '') AS [natura_sdi] "
    "FROM [FatturazioneElettronica_Data].[dbo].[fatture_inviate_righe] r "
    "LEFT JOIN [FatturazioneElettronica_Data].[dbo].[unita_misura] um ON r.unita_misura_id = um.id "
    "LEFT JOIN [FatturazioneElettronica_Data].[dbo].[codici_iva]  ci ON r.codice_iva_id   = ci.id "
    "WHERE r.fattura_id = @fattura_id "
    "ORDER BY r.riga ASC"
)

SQL_SCADENZE = (
    "SELECT s.[id] AS [id], s.[fattura_inviata_id] AS [fattura_inviata_id], "
    "s.[rata_n] AS [rata_n], s.[rata_totale] AS [rata_totale], "
    "s.[data_scadenza] AS [data_scadenza], s.[importo] AS [importo], "
    "s.[stato] AS [stato], "
    "ISNULL(pg.[descrizione], '') AS [pagamento_descrizione], "
    "ISNULL(b.[descrizione], '')  AS [banca_descrizione], "
    "ISNULL(b.[iban], '')         AS [banca_iban], "
    "ISNULL(b.[bic_swift], '')    AS [banca_bic] "
    "FROM [FatturazioneElettronica_Data].[dbo].[scadenze] s "
    "LEFT JOIN [FatturazioneElettronica_Data].[dbo].[pagamenti] pg ON s.pagamento_id = pg.id "
    "LEFT JOIN [FatturazioneElettronica_Data].[dbo].[banche] b    ON s.banca_id     = b.id "
    "WHERE COALESCE(s.cancellato, 0) = 0 AND s.fattura_inviata_id = @fattura_id "
    "ORDER BY s.rata_n ASC"
)

# Aggregato IVA (group by aliquota+natura) — calcolato da `fatture_inviate_righe`.
SQL_RIEPILOGO_IVA = (
    "SELECT "
    "ISNULL(ci.[aliquota], 0)  AS aliquota, "
    "ISNULL(ci.[natura_sdi], '') AS natura_sdi, "
    "ISNULL(ci.[descrizione], '') AS natura_descr, "
    "SUM(r.imponibile_riga)    AS imponibile_tot, "
    "SUM(r.iva_riga)           AS iva_tot "
    "FROM [FatturazioneElettronica_Data].[dbo].[fatture_inviate_righe] r "
    "LEFT JOIN [FatturazioneElettronica_Data].[dbo].[codici_iva] ci ON r.codice_iva_id = ci.id "
    "WHERE r.fattura_id = @fattura_id "
    "GROUP BY ci.aliquota, ci.natura_sdi, ci.descrizione "
    "ORDER BY ci.aliquota DESC, ci.natura_sdi"
)

# ── Helpers ─────────────────────────────────────────────────────────────

def encode_logo_b64() -> str:
    if not LOGO_PATH.exists():
        raise FileNotFoundError(f"Logo non trovato: {LOGO_PATH}")
    with open(LOGO_PATH, 'rb') as fh:
        return base64.b64encode(fh.read()).decode('ascii')


def text_component(name: str, x, y, w, h, expr: str, *,
                   font='Arial,8', font_bold=False,
                   align='Left', valign='Center',
                   bg='Transparent', border='None;Black;1;Solid;False;4;Black',
                   text_color='Black', is_expression=True,
                   parent_ref: int, page_ref: int = 8,
                   ref: int) -> str:
    """Generate a <Text> component XML block."""
    font_full = font + (',Bold' if font_bold else '')
    typ = 'Expression' if is_expression else 'Text'
    xml_text = expr.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    return dedent(f"""
        <{name} Ref="{ref}" type="Text" isKey="true">
          <Border>{border}</Border>
          <Brush>{bg}</Brush>
          <ClientRectangle>{x},{y},{w},{h}</ClientRectangle>
          <Conditions isList="true" count="0" />
          <Expressions isList="true" count="0" />
          <Font>{font_full}</Font>
          <HorAlignment>{align}</HorAlignment>
          <Name>{name}</Name>
          <Page isRef="{page_ref}" />
          <Parent isRef="{parent_ref}" />
          <Text>{xml_text}</Text>
          <TextBrush>{text_color}</TextBrush>
          <Type>{typ}</Type>
          <VertAlignment>{valign}</VertAlignment>
          <WordWrap>True</WordWrap>
          <CanGrow>True</CanGrow>
        </{name}>""").strip()


def image_component(name: str, x, y, w, h, image_b64: str, *,
                    parent_ref: int, page_ref: int = 8, ref: int) -> str:
    return dedent(f"""
        <{name} Ref="{ref}" type="Image" isKey="true">
          <AspectRatio>True</AspectRatio>
          <Border>None;Black;1;Solid;False;4;Black</Border>
          <Brush>Transparent</Brush>
          <ClientRectangle>{x},{y},{w},{h}</ClientRectangle>
          <Conditions isList="true" count="0" />
          <Expressions isList="true" count="0" />
          <Image>{image_b64}</Image>
          <Name>{name}</Name>
          <Page isRef="{page_ref}" />
          <Parent isRef="{parent_ref}" />
          <Stretch>True</Stretch>
        </{name}>""").strip()


# ── Build the report ────────────────────────────────────────────────────

def build_report() -> str:
    logo_b64 = encode_logo_b64()

    # Counter for unique component refs (start after fixed refs 1-99 reserved
    # for skeleton). Bands consume refs in order, components inside bands
    # come after.
    next_ref = [200]
    def nref() -> int:
        v = next_ref[0]
        next_ref[0] += 1
        return v

    # Page geometry: A4 portrait 21x29.7cm; usable width with .5cm margins ~ 20cm.
    PW = 19.0  # working width in cm (matches existing report)

    # ── ReportTitleBand: header + FORNITORE/CLIENTE boxes ─────────────
    # Strategia: tutto il contenuto a record-singolo in ReportTitleBand
    # (printa esattamente 1 volta). Evita il master DataBand che Stimulsoft
    # itera 2 volte per ragioni interne quando ha multiple detail children.
    title_band_ref = 9
    title_components = []

    # FATTURA header right-aligned
    title_components.append(text_component(
        'TitleFattura', PW - 5, 0, 5, 0.7, 'FATTURA',
        font='Arial,18', font_bold=True, align='Right',
        parent_ref=title_band_ref, ref=nref(), is_expression=False,
    ))
    title_components.append(text_component(
        'TitleNumero', PW - 6, 0.75, 6, 0.4,
        '{"nr. " + fatture_inviate.numero + " del " + fatture_inviate.data_documento.ToString("dd/MM/yyyy")}',
        font='Arial,9', align='Right',
        parent_ref=title_band_ref, ref=nref(),
    ))
    title_components.append(text_component(
        'TitleDataInvio', PW - 6, 1.15, 6, 0.4,
        '{"Data invio: " + (fatture_inviate.data_invio == null ? fatture_inviate.data_documento.ToString("dd/MM/yyyy") : fatture_inviate.data_invio.ToString("dd/MM/yyyy"))}',
        font='Arial,9', align='Right',
        parent_ref=title_band_ref, ref=nref(),
    ))

    # FORNITORE/CLIENTE boxes — ora INSIDE ReportTitleBand (1 print only).
    # Posizionati a y=1.85 dentro la title band.
    BOX_BG = '[235:240:245:255]'  # light gray
    half = (PW - 0.4) / 2  # box width with 0.4cm gap
    BY = 1.85  # base y for boxes

    title_components.append(text_component(
        'LblFornitore', 0, BY, half, 0.5, 'FORNITORE',
        font='Arial,11', font_bold=True, align='Left',
        bg=BOX_BG, parent_ref=title_band_ref, ref=nref(), is_expression=False,
    ))
    forn_lines = [
        ('FoSupp1', 'FatturazioneElettronica Test SRL', True),
        ('FoSupp2', 'P.IVA: IT00000000000', False),
        ('FoSupp3', 'C.F.: 00000000000', False),
        ('FoSupp4', 'Via Esempio 1', False),
        ('FoSupp5', '00100 - Roma (RM) - IT', False),
    ]
    fy = BY + 0.55
    for nm, txt, bold in forn_lines:
        title_components.append(text_component(
            nm, 0.1, fy, half - 0.2, 0.4, txt,
            font='Arial,9', font_bold=bold, align='Left', valign='Center',
            bg=BOX_BG, parent_ref=title_band_ref, ref=nref(), is_expression=False,
        ))
        fy += 0.4

    # Cliente (right) — espressioni semplici 1-per-riga
    title_components.append(text_component(
        'LblCliente', half + 0.4, BY, half, 0.5, 'CLIENTE',
        font='Arial,11', font_bold=True, align='Left',
        bg=BOX_BG, parent_ref=title_band_ref, ref=nref(), is_expression=False,
    ))
    # Espressioni semplici: concatenazione + raw field (no ternaria con null
    # check — Stimulsoft compila ma il null-check su denormalized join cols
    # ritorna empty string anche quando i dati ci sono, vedi nota generator).
    cli_lines = [
        ('CliRS',   '{fatture_inviate.clienti___ragione_sociale__cliente_id}', True),
        ('CliPiva', '{(fatture_inviate.cli_piva == "" ? "" : "P.IVA: " + fatture_inviate.cli_piva)}', False),
        ('CliCf',   '{(fatture_inviate.cli_cf == "" ? "" : "C.F.: " + fatture_inviate.cli_cf)}', False),
        ('CliInd',  '{fatture_inviate.cli_indirizzo}', False),
        ('CliLoc',  '{fatture_inviate.cli_cap + " - " + fatture_inviate.cli_citta + (fatture_inviate.cli_prov == "" ? "" : " (" + fatture_inviate.cli_prov + ")") + " - " + fatture_inviate.cli_naz}', False),
        ('CliCD',   '{(fatture_inviate.cli_cd == "" ? "" : "Codice destinatario: " + fatture_inviate.cli_cd)}', False),
    ]
    cy = BY + 0.55
    for nm, expr, bold in cli_lines:
        title_components.append(text_component(
            nm, half + 0.5, cy, half - 0.2, 0.4, expr,
            font='Arial,9', font_bold=bold, align='Left', valign='Center',
            bg=BOX_BG, parent_ref=title_band_ref, ref=nref(),
        ))
        cy += 0.4

    title_band = dedent(f"""
        <ReportTitleBand1 Ref="{title_band_ref}" type="ReportTitleBand" isKey="true">
          <Brush>Transparent</Brush>
          <ClientRectangle>0,0,{PW},5.0</ClientRectangle>
          <Components isList="true" count="{len(title_components)}">
            {chr(10).join(title_components)}
          </Components>
          <Conditions isList="true" count="0" />
          <Expressions isList="true" count="0" />
          <Name>ReportTitleBand1</Name>
          <Page isRef="8" />
          <Parent isRef="8" />
        </ReportTitleBand1>""").strip()
    info_band = ''  # bands removed - merged into title_band

    # ── HeaderBand: PRODOTTI E SERVIZI title + table header ──────────────
    prod_hdr_ref = 11
    HDR_BG = '[230:230:230:230]'

    p_title = text_component(
        'LblProdottiTitle', 0, 0, PW, 0.55, 'PRODOTTI E SERVIZI',
        font='Arial,12', font_bold=True, align='Center',
        parent_ref=prod_hdr_ref, ref=nref(), is_expression=False,
    )
    # Column widths (sum = 19): NR(1) DESCRIZIONE(8) QTA(2) PREZZO(2) IMPORTO(2.5) IVA(1.5) NATURA(2)
    cols_p = [
        ('hNR', 'NR', 'Center'),
        ('hDescr', 'DESCRIZIONE', 'Left'),
        ('hQta', "QUANTITA'", 'Center'),
        ('hPrezzo', 'PREZZO', 'Right'),
        ('hImp', 'IMPORTO', 'Right'),
        ('hIva', 'IVA', 'Right'),
        ('hNat', 'NATURA IVA', 'Center'),
    ]
    widths_p = [1, 8, 2, 2, 2.5, 1.5, 2]
    p_headers = []
    cx = 0.0
    for (nm, lbl, al), w in zip(cols_p, widths_p):
        p_headers.append(text_component(
            nm, cx, 0.55, w, 0.45, lbl,
            font='Arial,8', font_bold=True, align=al,
            bg=HDR_BG, border='Bottom;Black;1;Solid;False;4;Black',
            parent_ref=prod_hdr_ref, ref=nref(), is_expression=False,
        ))
        cx += w

    prod_hdr = dedent(f"""
        <HeaderProdottiBand Ref="{prod_hdr_ref}" type="HeaderBand" isKey="true">
          <Brush>Transparent</Brush>
          <ClientRectangle>0,4.85,{PW},1.0</ClientRectangle>
          <Components isList="true" count="{1 + len(p_headers)}">
            {p_title}
            {chr(10).join(p_headers)}
          </Components>
          <Conditions isList="true" count="0" />
          <Expressions isList="true" count="0" />
          <Name>HeaderProdottiBand</Name>
          <Page isRef="8" />
          <Parent isRef="8" />
        </HeaderProdottiBand>""").strip()

    # ── DataBand on righe ────────────────────────────────────────────────
    righe_band_ref = 12
    cells_p = [
        ('cNr',     '{fatture_inviate_righe.riga}', 'Center'),
        ('cDescr',  '{fatture_inviate_righe.descrizione}', 'Left'),
        ('cQta',    '{fatture_inviate_righe.quantita.ToString("N2")}', 'Center'),
        ('cPrezzo', '{fatture_inviate_righe.prezzo_unitario.ToString("N2") + " €"}', 'Right'),
        ('cImp',    '{fatture_inviate_righe.imponibile_riga.ToString("N2") + " €"}', 'Right'),
        ('cIva',    '{fatture_inviate_righe.aliquota.ToString("N0") + " %"}', 'Right'),
        ('cNat',    '{fatture_inviate_righe.natura_sdi}', 'Center'),
    ]
    p_cells = []
    cx = 0.0
    for (nm, expr, al), w in zip(cells_p, widths_p):
        p_cells.append(text_component(
            nm, cx, 0, w, 0.5, expr,
            font='Arial,8', align=al,
            border='Bottom;[230:230:230:230];0.5;Solid;False;4;Black',
            parent_ref=righe_band_ref, ref=nref(),
        ))
        cx += w

    # No DataRelationName: la SQL e' gia' filtrata da @fattura_id, niente
    # DataRelations dichiarate -> il DataBand itera tutto il result-set della
    # SQL filtrata. Evita il fanout duplicato del master quando ci sono piu'
    # DataRelations sulla stessa source.
    righe_band = dedent(f"""
        <RigheDataBand Ref="{righe_band_ref}" type="DataBand" isKey="true">
          <Brush>Transparent</Brush>
          <BusinessObjectGuid isNull="true" />
          <ClientRectangle>0,5.85,{PW},0.5</ClientRectangle>
          <Components isList="true" count="{len(p_cells)}">
            {chr(10).join(p_cells)}
          </Components>
          <Conditions isList="true" count="0" />
          <DataSourceName>fatture_inviate_righe</DataSourceName>
          <Expressions isList="true" count="0" />
          <Name>RigheDataBand</Name>
          <Page isRef="8" />
          <Parent isRef="8" />
        </RigheDataBand>""").strip()

    # ── HeaderBand: METODO DI PAGAMENTO ─────────────────────────────────
    pag_hdr_ref = 13
    pag_title = text_component(
        'LblPagamentoTitle', 0, 0, PW, 0.55, 'METODO DI PAGAMENTO',
        font='Arial,12', font_bold=True, align='Center',
        parent_ref=pag_hdr_ref, ref=nref(), is_expression=False,
    )
    cols_s = [
        ('shRata', 'NR RATA', 'Center'),
        ('shMod',  'MODALITÀ', 'Left'),
        ('shPag',  'PAGAMENTO', 'Left'),
        ('shBan',  'BANCA', 'Left'),
        ('shIban', 'IBAN', 'Left'),
        ('shBic',  'BIC/SWIFT', 'Left'),
        ('shData', 'DATA SCADENZA', 'Center'),
        ('shImp',  'IMPORTO', 'Right'),
    ]
    widths_s = [1.2, 1.8, 2.5, 2.5, 5, 1.7, 2.3, 2]
    s_headers = []
    cx = 0.0
    for (nm, lbl, al), w in zip(cols_s, widths_s):
        s_headers.append(text_component(
            nm, cx, 0.55, w, 0.45, lbl,
            font='Arial,8', font_bold=True, align=al,
            bg=HDR_BG, border='Bottom;Black;1;Solid;False;4;Black',
            parent_ref=pag_hdr_ref, ref=nref(), is_expression=False,
        ))
        cx += w

    # HeaderBand attached alla ScadenzeDataBand: stampa solo quando scadenze ha
    # righe. Comportamento corretto per "METODO DI PAGAMENTO" (sezione
    # significativa solo se ci sono rate).
    pag_hdr = dedent(f"""
        <HeaderPagamentoBand Ref="{pag_hdr_ref}" type="HeaderBand" isKey="true">
          <Brush>Transparent</Brush>
          <ClientRectangle>0,6.4,{PW},1.0</ClientRectangle>
          <Components isList="true" count="{1 + len(s_headers)}">
            {pag_title}
            {chr(10).join(s_headers)}
          </Components>
          <Conditions isList="true" count="0" />
          <Expressions isList="true" count="0" />
          <Name>HeaderPagamentoBand</Name>
          <Page isRef="8" />
          <Parent isRef="8" />
        </HeaderPagamentoBand>""").strip()

    # ── DataBand on scadenze ────────────────────────────────────────────
    scad_band_ref = 14
    cells_s = [
        ('csRata', '{scadenze.rata_n + "/" + scadenze.rata_totale}', 'Center'),
        ('csMod',  '{scadenze.pagamento_descrizione}', 'Left'),
        ('csPag',  '{(scadenze.rata_totale > 1 ? "Rata " + scadenze.rata_n + "/" + scadenze.rata_totale : "Pagamento in unica soluzione")}', 'Left'),
        ('csBan',  '{scadenze.banca_descrizione}', 'Left'),
        ('csIban', '{scadenze.banca_iban}', 'Left'),
        ('csBic',  '{scadenze.banca_bic}', 'Left'),
        ('csData', '{scadenze.data_scadenza.ToString("dd/MM/yyyy")}', 'Center'),
        ('csImp',  '{scadenze.importo.ToString("N2") + " €"}', 'Right'),
    ]
    s_cells = []
    cx = 0.0
    for (nm, expr, al), w in zip(cells_s, widths_s):
        s_cells.append(text_component(
            nm, cx, 0, w, 0.5, expr,
            font='Arial,8', align=al,
            border='Bottom;[230:230:230:230];0.5;Solid;False;4;Black',
            parent_ref=scad_band_ref, ref=nref(),
        ))
        cx += w

    scad_band = dedent(f"""
        <ScadenzeDataBand Ref="{scad_band_ref}" type="DataBand" isKey="true">
          <Brush>Transparent</Brush>
          <BusinessObjectGuid isNull="true" />
          <ClientRectangle>0,7.4,{PW},0.5</ClientRectangle>
          <Components isList="true" count="{len(s_cells)}">
            {chr(10).join(s_cells)}
          </Components>
          <Conditions isList="true" count="0" />
          <DataSourceName>scadenze</DataSourceName>
          <Expressions isList="true" count="0" />
          <Name>ScadenzeDataBand</Name>
          <Page isRef="8" />
          <Parent isRef="8" />
        </ScadenzeDataBand>""").strip()

    # ── REGIME FISCALE + DATI AGGIUNTIVI ─────────────────────────────────
    # Sezioni "post-detail" senza DataBand seguente: vengono incorporate
    # nella ReportSummaryBand sotto, che stampa una volta sola al termine
    # del master loop e ha accesso al row context di fatture_inviate.
    # (Stimulsoft non permette HeaderBand orfani: vengono auto-nascosti.)

    # ── ReportSummaryBand: RF + DA + RIEPILOGO IVA + CALCOLO FATTURA + Netto ─
    # Stampa una volta a fine report (dopo l'ultima iterazione del master).
    # Ha accesso al row context di fatture_inviate (master) e include 3
    # sezioni stack verticale: REGIME FISCALE, DATI AGGIUNTIVI, RIEPILOGO/CALCOLO.
    sum_band_ref = 15
    sum_components = []

    # 1) REGIME FISCALE
    sum_components.append(text_component(
        'LblRfTitle', 0, 0, PW, 0.55, 'REGIME FISCALE',
        font='Arial,12', font_bold=True, align='Center',
        parent_ref=sum_band_ref, ref=nref(), is_expression=False,
    ))
    sum_components.append(text_component(
        'TxtRf', 0, 0.6, PW, 0.9,
        '{(fatture_inviate.causali___descrizione__causale_id == null || fatture_inviate.causali___descrizione__causale_id == "") ? "RF01 - Regime ordinario" : fatture_inviate.causali___descrizione__causale_id}',
        font='Arial,9', align='Left', valign='Top',
        parent_ref=sum_band_ref, ref=nref(),
    ))

    # 2) DATI AGGIUNTIVI: titolo + 2 colonne (bollo + causale)
    sum_components.append(text_component(
        'LblDaTitle', 0, 1.6, PW, 0.55, 'DATI AGGIUNTIVI',
        font='Arial,12', font_bold=True, align='Center',
        parent_ref=sum_band_ref, ref=nref(), is_expression=False,
    ))
    sum_components.append(text_component(
        'LblBollo', 0, 2.2, half, 0.4, 'DATI BOLLO',
        font='Arial,9', font_bold=True, align='Left',
        parent_ref=sum_band_ref, ref=nref(), is_expression=False,
    ))
    sum_components.append(text_component(
        'TxtBollo', 0, 2.6, half, 0.9,
        ('{(fatture_inviate.bollo_valore == null || fatture_inviate.bollo_valore <= 0) ? '
         '"Nessun bollo applicato" : '
         '"Importo " + fatture_inviate.bollo_valore.ToString("N2") + " EUR: Imposta di bollo assolta in modo virtuale ai sensi dell\\u0027art. 15 del D.P.R. 642/1972 e del DM 17/06/2014 e ss.mm."}'),
        font='Arial,8', align='Left', valign='Top',
        parent_ref=sum_band_ref, ref=nref(),
    ))
    sum_components.append(text_component(
        'LblCausale', half + 0.4, 2.2, half, 0.4, 'CAUSALE DOCUMENTO',
        font='Arial,9', font_bold=True, align='Left',
        parent_ref=sum_band_ref, ref=nref(), is_expression=False,
    ))
    sum_components.append(text_component(
        'TxtCausale', half + 0.4, 2.6, half, 0.9,
        '{(fatture_inviate.causale == null || fatture_inviate.causale == "") ? "" : fatture_inviate.causale}',
        font='Arial,8', align='Left', valign='Top',
        parent_ref=sum_band_ref, ref=nref(),
    ))

    # 3) RIEPILOGO IVA | CALCOLO FATTURA — y offset = 3.7
    SY = 3.7  # summary y offset for RIEPILOGO/CALCOLO subsection
    sum_title_left = text_component(
        'LblRiepIva', 0, SY, half, 0.55, 'RIEPILOGO IVA',
        font='Arial,12', font_bold=True, align='Center',
        parent_ref=sum_band_ref, ref=nref(), is_expression=False,
    )
    sum_title_right = text_component(
        'LblCalcolo', half + 0.4, SY, half, 0.55, 'CALCOLO FATTURA',
        font='Arial,12', font_bold=True, align='Center',
        parent_ref=sum_band_ref, ref=nref(), is_expression=False,
    )

    sum_components.append(sum_title_left)
    sum_components.append(sum_title_right)

    # CALCOLO FATTURA (right column)
    rows_calc = [
        ('Importo prodotti o servizi', '{fatture_inviate.imponibile.ToString("N2") + " EUR"}'),
        ('Totale imponibile',          '{fatture_inviate.imponibile.ToString("N2") + " EUR"}'),
        ('Totale IVA',                 '{fatture_inviate.iva.ToString("N2") + " EUR"}'),
    ]
    cy = SY + 0.6
    for label, expr in rows_calc:
        sum_components.append(text_component(
            f'CL_{label[:6].replace(" ", "_")}', half + 0.4, cy, half * 0.6, 0.45, label,
            font='Arial,9', align='Left',
            parent_ref=sum_band_ref, ref=nref(), is_expression=False,
        ))
        sum_components.append(text_component(
            f'CV_{label[:6].replace(" ", "_")}', half + 0.4 + half * 0.6, cy, half * 0.4, 0.45, expr,
            font='Arial,9', align='Right',
            parent_ref=sum_band_ref, ref=nref(),
        ))
        cy += 0.45

    cy_tot = cy
    sum_components.append(text_component(
        'CL_TOTALE', half + 0.4, cy_tot, half * 0.6, 0.55, 'Totale documento',
        font='Arial,10', font_bold=True, align='Left',
        border='Top;Black;1;Solid;False;4;Black',
        parent_ref=sum_band_ref, ref=nref(), is_expression=False,
    ))
    sum_components.append(text_component(
        'CV_TOTALE', half + 0.4 + half * 0.6, cy_tot, half * 0.4, 0.55,
        '{fatture_inviate.totale.ToString("N2") + " EUR"}',
        font='Arial,10', font_bold=True, align='Right',
        border='Top;Black;1;Solid;False;4;Black',
        parent_ref=sum_band_ref, ref=nref(),
    ))
    cy = cy_tot + 0.55

    # Netto a pagare (full-width row, large bold)
    sum_components.append(text_component(
        'NettoLbl', half + 0.4, cy + 0.3, half * 0.5, 0.7, 'Netto a pagare',
        font='Arial,14', font_bold=True, align='Left',
        parent_ref=sum_band_ref, ref=nref(), is_expression=False,
    ))
    sum_components.append(text_component(
        'NettoVal', half + 0.4 + half * 0.5, cy + 0.3, half * 0.5, 0.7,
        '{fatture_inviate.totale.ToString("N2") + " EUR"}',
        font='Arial,14', font_bold=True, align='Right',
        parent_ref=sum_band_ref, ref=nref(),
    ))

    # RIEPILOGO IVA (left column): riepilogo sintetico
    rows_riep = [
        ('Aliquota base IVA',  '{fatture_inviate.iva > 0 ? "Aliquota mista" : "0% (esenti / non imp.)"}'),
        ('Imponibile totale',  '{fatture_inviate.imponibile.ToString("N2") + " EUR"}'),
        ('Imposta totale',     '{fatture_inviate.iva.ToString("N2") + " EUR"}'),
    ]
    rcy = SY + 0.6
    for label, expr in rows_riep:
        sum_components.append(text_component(
            f'RL_{label[:6].replace(" ", "_")}', 0, rcy, half * 0.55, 0.45, label,
            font='Arial,9', align='Left',
            parent_ref=sum_band_ref, ref=nref(), is_expression=False,
        ))
        sum_components.append(text_component(
            f'RV_{label[:6].replace(" ", "_")}', 0 + half * 0.55, rcy, half * 0.45, 0.45, expr,
            font='Arial,9', align='Right',
            parent_ref=sum_band_ref, ref=nref(),
        ))
        rcy += 0.45

    sum_band = dedent(f"""
        <ReportSummaryBand1 Ref="{sum_band_ref}" type="ReportSummaryBand" isKey="true">
          <Brush>Transparent</Brush>
          <ClientRectangle>0,8,{PW},8.5</ClientRectangle>
          <Components isList="true" count="{len(sum_components)}">
            {chr(10).join(sum_components)}
          </Components>
          <Conditions isList="true" count="0" />
          <Expressions isList="true" count="0" />
          <Name>ReportSummaryBand1</Name>
          <Page isRef="8" />
          <Parent isRef="8" />
        </ReportSummaryBand1>""").strip()

    # ── PageFooterBand: disclaimer + WUIC logo + page number ────────────
    foot_band_ref = 16
    foot_disc = text_component(
        'FootDisc', 0, 0, PW, 0.4,
        'Copia analogica della fattura elettronica inviata a SdI | Il documento xml originale è disponibile online sul portale "Fatture e Corrispettivi dell\'Agenzia delle Entrate"',
        font='Arial,7', align='Center', valign='Top', text_color='[120:120:120:255]',
        parent_ref=foot_band_ref, ref=nref(), is_expression=False,
    )
    # Numero fattura sx
    foot_num = text_component(
        'FootNum', 0, 0.55, PW * 0.35, 0.5,
        '{"Fattura nr. " + fatture_inviate.numero + " del " + fatture_inviate.data_documento.ToString("dd/MM/yyyy")}',
        font='Arial,7', align='Left', text_color='[120:120:120:255]',
        parent_ref=foot_band_ref, ref=nref(),
    )
    # "Fattura generata con:" centro
    foot_gen = text_component(
        'FootGen', PW * 0.35, 0.55, PW * 0.18, 0.5,
        'Fattura generata con:',
        font='Arial,7', align='Right', text_color='[120:120:120:255]',
        parent_ref=foot_band_ref, ref=nref(), is_expression=False,
    )
    # Logo WUIC (PNG embedded)
    foot_logo = image_component(
        'FootLogo', PW * 0.53, 0.45, 3.5, 0.7, logo_b64,
        parent_ref=foot_band_ref, ref=nref(),
    )
    # Pag X/Y dx
    foot_page = text_component(
        'FootPage', PW - 1.5, 0.55, 1.5, 0.5,
        '{"Pag." + Page.ToString() + "/" + TotalPageCount.ToString()}',
        font='Arial,7', align='Right', text_color='[120:120:120:255]',
        parent_ref=foot_band_ref, ref=nref(),
    )

    foot_band = dedent(f"""
        <PageFooterBand1 Ref="{foot_band_ref}" type="PageFooterBand" isKey="true">
          <Brush>Transparent</Brush>
          <ClientRectangle>0,28,{PW},1.4</ClientRectangle>
          <Components isList="true" count="5">
            {foot_disc}
            {foot_num}
            {foot_gen}
            {foot_logo}
            {foot_page}
          </Components>
          <Conditions isList="true" count="0" />
          <Expressions isList="true" count="0" />
          <Name>PageFooterBand1</Name>
          <Page isRef="8" />
          <Parent isRef="8" />
        </PageFooterBand1>""").strip()

    # ── Assemble Page1 ──────────────────────────────────────────────────
    # 7 bande: Title (FATTURA + FORNITORE/CLIENTE — print-once), HeaderProdotti,
    # RigheDetail, HeaderPagamento, ScadenzeDetail, ReportSummary (RF+DA+
    # Riep+Calcolo+Netto), PageFooter (disclaimer + WUIC logo).
    page1 = dedent(f"""
        <Page1 Ref="8" type="Page" isKey="true">
          <Border>None;Black;2;Solid;False;4;Black</Border>
          <Brush>Transparent</Brush>
          <Components isList="true" count="7">
            {title_band}
            {prod_hdr}
            {righe_band}
            {pag_hdr}
            {scad_band}
            {sum_band}
            {foot_band}
          </Components>
          <Conditions isList="true" count="0" />
          <ExcelSheetValue isNull="true" />
          <Guid>guid-page1-fattura-2026</Guid>
          <Margins>0.5,0.5,0.5,0.5</Margins>
          <Name>Page1</Name>
          <PageHeight>29.7</PageHeight>
          <PageWidth>21</PageWidth>
          <PaperSize>A4</PaperSize>
          <Report isRef="0" />
          <SegmentPerHeight>1</SegmentPerHeight>
          <SegmentPerWidth>1</SegmentPerWidth>
          <Watermark Ref="99" type="Stimulsoft.Report.Components.StiWatermark" isKey="true">
            <Font>Arial,100,Bold</Font>
            <TextBrush>[50:0:0:0]</TextBrush>
          </Watermark>
        </Page1>""").strip()

    # ── Dictionary (datasources + parameter) ────────────────────────────
    # CRITICAL: <Columns isList="true"> declaration is REQUIRED — Stimulsoft
    # uses it to resolve `{datasource.field}` expressions at compile time.
    # Senza la dichiarazione, le espressioni falliscono silenziosamente
    # (campo letto come null/empty -> box vuoti nel rendering).
    # Format: (col_name, source_table_hint_or_None, dotnet_type)
    # Quando source_table_hint != None, Stimulsoft genera "<col>,<hint>,<type>"
    # (3-part) altrimenti "<col>,<type>" (2-part). I JOINed columns
    # richiedono il 3-part format perche' Stimulsoft StiSqlSource lo usa
    # per il binding runtime: senza il hint, le colonne aliasate non
    # vengono lette dal result-set (verificato 2026-05-09 - duplicate
    # render quando 2-part causa fallback su prima-row only).
    # FK columns con lookup-type hint (formato `<col>_id_lookup`) — Stimulsoft
    # usa questo hint per riconoscere la JOIN-source e binda correttamente
    # le denormalized join columns. Senza FK declaration, le denormalized
    # cols (es. `clienti___partita_iva__cliente_id`) ritornano empty anche
    # se SQL le restituisce. Vedi Report_NEW.mrt originale per il pattern.
    fatt_cols = [
        ('id', None, 'System.Double'),
        ('numero', None, 'System.String'),
        ('serie', None, 'System.String'),
        ('progressivo', None, 'System.Double'),
        ('anno', None, 'System.Double'),
        ('data_documento', None, 'System.DateTime'),
        # FK declarations con lookup-type
        ('cliente_id', 'cliente_id_id_lookup', 'System.Double'),
        ('pagamento_id', 'pagamento_id_id_lookup', 'System.Double'),
        ('banca_id', 'banca_id_id_lookup', 'System.Double'),
        ('causale_id', 'causale_id_id_lookup', 'System.Double'),
        # Cliente: ragione_sociale via WUIC lookup convention; altri come
        # plain string columns con prefisso `cli_` (vedi nota in SQL_FATTURA).
        ('clienti___ragione_sociale__cliente_id', 'clienti', 'System.String'),
        ('cli_piva', None, 'System.String'),
        ('cli_cf', None, 'System.String'),
        ('cli_indirizzo', None, 'System.String'),
        ('cli_cap', None, 'System.String'),
        ('cli_citta', None, 'System.String'),
        ('cli_prov', None, 'System.String'),
        ('cli_naz', None, 'System.String'),
        ('cli_cd', None, 'System.String'),
        ('cli_email', None, 'System.String'),
        ('cli_pec', None, 'System.String'),
        ('pagamenti___descrizione__pagamento_id', 'pagamenti', 'System.String'),
        ('pagamenti___codice_sdi__pagamento_id', 'pagamenti', 'System.String'),
        ('banche___descrizione__banca_id', 'banche', 'System.String'),
        ('banche___iban__banca_id', 'banche', 'System.String'),
        ('banche___bic_swift__banca_id', 'banche', 'System.String'),
        ('causale', None, 'System.String'),
        ('causali___descrizione__causale_id', 'causali', 'System.String'),
        ('bollo_valore', None, 'System.Double'),
        ('imponibile', None, 'System.Double'),
        ('iva', None, 'System.Double'),
        ('totale', None, 'System.Double'),
        ('stato', None, 'System.String'),
        ('stato_sdi', None, 'System.String'),
        ('data_invio', None, 'System.DateTime'),
    ]
    righe_cols = [
        ('id', None, 'System.Double'),
        ('fattura_id', None, 'System.Double'),
        ('riga', None, 'System.Double'),
        ('descrizione', None, 'System.String'),
        ('quantita', None, 'System.Double'),
        ('um_codice', 'unita_misura', 'System.String'),
        ('prezzo_unitario', None, 'System.Double'),
        ('sconto_perc', None, 'System.Double'),
        ('imponibile_riga', None, 'System.Double'),
        ('iva_riga', None, 'System.Double'),
        ('totale_riga', None, 'System.Double'),
        ('aliquota', 'codici_iva', 'System.Double'),
        ('natura_sdi', 'codici_iva', 'System.String'),
    ]
    scad_cols = [
        ('id', None, 'System.Double'),
        ('fattura_inviata_id', None, 'System.Double'),
        ('rata_n', None, 'System.Double'),
        ('rata_totale', None, 'System.Double'),
        ('data_scadenza', None, 'System.DateTime'),
        ('importo', None, 'System.Double'),
        ('stato', None, 'System.String'),
        ('pagamento_descrizione', 'pagamenti', 'System.String'),
        ('banca_descrizione', 'banche', 'System.String'),
        ('banca_iban', 'banche', 'System.String'),
        ('banca_bic', 'banche', 'System.String'),
    ]

    def cols_xml(cols):
        def fmt(c):
            name, hint, typ = c
            if hint:
                return f'<value>{name},{hint},{typ}</value>'
            return f'<value>{name},{typ}</value>'
        items = '\n              '.join(fmt(c) for c in cols)
        return (f'<Columns isList="true" count="{len(cols)}">\n              '
                f'{items}\n            </Columns>')

    fatt_cols_xml = cols_xml(fatt_cols)
    righe_cols_xml = cols_xml(righe_cols)
    scad_cols_xml = cols_xml(scad_cols)

    dictionary = dedent(f"""
        <Dictionary Ref="1" type="Dictionary" isKey="true">
          <BusinessObjects isList="true" count="0" />
          <Databases isList="true" count="1">
            <Connessione Ref="2" type="Stimulsoft.Report.Dictionary.StiSqlDatabase" isKey="true">
              <Alias>Connessione</Alias>
              <ConnectionStringEncrypted>{CONN_STRING_ENC}</ConnectionStringEncrypted>
              <Name>Connessione</Name>
            </Connessione>
          </Databases>
          <DataSources isList="true" count="3">
            <fatture_inviate Ref="3" type="Stimulsoft.Report.Dictionary.StiSqlSource" isKey="true">
              <Alias>fatture_inviate</Alias>
              {fatt_cols_xml}
              <CommandTimeout>300</CommandTimeout>
              <Dictionary isRef="1" />
              <Key>fa0509a1b2c3d4e5f60718293a4b5c6d</Key>
              <Name>fatture_inviate</Name>
              <NameInSource>Connessione</NameInSource>
              <Parameters isList="true" count="0" />
              <SqlCommand>{SQL_FATTURA}</SqlCommand>
            </fatture_inviate>
            <fatture_inviate_righe Ref="4" type="Stimulsoft.Report.Dictionary.StiSqlSource" isKey="true">
              <Alias>fatture_inviate_righe</Alias>
              {righe_cols_xml}
              <CommandTimeout>300</CommandTimeout>
              <Dictionary isRef="1" />
              <Key>fa0509a2b2c3d4e5f60718293a4b5c6d</Key>
              <Name>fatture_inviate_righe</Name>
              <NameInSource>Connessione</NameInSource>
              <Parameters isList="true" count="0" />
              <SqlCommand>{SQL_RIGHE}</SqlCommand>
            </fatture_inviate_righe>
            <scadenze Ref="5" type="Stimulsoft.Report.Dictionary.StiSqlSource" isKey="true">
              <Alias>scadenze</Alias>
              {scad_cols_xml}
              <CommandTimeout>300</CommandTimeout>
              <Dictionary isRef="1" />
              <Key>fa0509a3b2c3d4e5f60718293a4b5c6d</Key>
              <Name>scadenze</Name>
              <NameInSource>Connessione</NameInSource>
              <Parameters isList="true" count="0" />
              <SqlCommand>{SQL_SCADENZE}</SqlCommand>
            </scadenze>
          </DataSources>
          <Relations isList="true" count="0" />
          <Report isRef="0" />
          <Resources isList="true" count="0" />
          <UserFunctions isList="true" count="0" />
          <Variables isList="true" count="1">
            <value>,fattura_id,fattura_id,,System.Int32,_x0030_,False,False,False,False,_x003C__x003F_xml_x0020_version_x003D__x0022_1.0_x0022__x0020_encoding_x003D__x0022_utf-16_x0022__x0020_standalone_x003D__x0022_no_x0022__x003F__x003E__x003C_StiSerializer_x0020_application_x003D__x0022_State_x0022__x003E__x003C_DateTimeType_x003E_DateAndTime_x003C__x002F_DateTimeType_x003E__x003C_SortDirection_x003E_None_x003C__x002F_SortDirection_x003E__x003C_BindingVariable_x0020_isNull_x003D__x0022_true_x0022__x0020__x002F__x003E__x003C_Keys_x0020_isList_x003D__x0022_true_x0022__x0020_count_x003D__x0022_0_x0022__x0020__x002F__x003E__x003C_Values_x0020_isList_x003D__x0022_true_x0022__x0020_count_x003D__x0022_0_x0022__x0020__x002F__x003E__x003C_CheckedStates_x0020_isList_x003D__x0022_true_x0022__x0020_count_x003D__x0022_0_x0022__x0020__x002F__x003E__x003C__x002F_StiSerializer_x003E_,,True</value>
          </Variables>
        </Dictionary>""").strip()

    # ── Final assembly ─────────────────────────────────────────────────
    return dedent(f"""<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<StiSerializer version="1.02" type="Net" application="StiReport">
  <CalculationMode>Interpretation</CalculationMode>
  {dictionary}
  <EngineVersion>EngineV2</EngineVersion>
  <GlobalizationStrings isList="true" count="0" />
  <Key>30f97278ee6941778aed5daf7338f57c</Key>
  <MetaTags isList="true" count="0" />
  <Pages isList="true" count="1">
    {page1}
  </Pages>
  <PreviewSettings>2097147</PreviewSettings>
  <ReferencedAssemblies isList="true" count="6">
    <value>System.Dll</value>
    <value>System.Drawing.Dll</value>
    <value>System.Windows.Forms.Dll</value>
    <value>System.Data.Dll</value>
    <value>System.Xml.Dll</value>
    <value>Stimulsoft.Report.Dll</value>
  </ReferencedAssemblies>
  <ReportAlias>FatturaReport</ReportAlias>
  <ReportAuthor>WUIC</ReportAuthor>
  <ReportChanged>{Path(__file__).name}</ReportChanged>
  <ReportCreated>2026-05-09</ReportCreated>
  <ReportDescription>Stampa fattura layout Aruba PEC FPR-style</ReportDescription>
  <ReportFile>Report.mrt</ReportFile>
  <ReportGuid>guid-fattura-aruba-pec-2026-05-09</ReportGuid>
  <ReportName>Report</ReportName>
  <ReportUnit>Centimeters</ReportUnit>
  <ReportVersion>2026.1.5</ReportVersion>
  <Script>using System;
using System.Drawing;
using System.Windows.Forms;
using System.Data;
using System.Globalization;
using System.Xml;
using Stimulsoft.Report;
using Stimulsoft.Report.Components;

namespace Reports
{{
    public class Report : Stimulsoft.Report.StiReport
    {{
        public Report() {{ this.InitializeComponent(); }}
        private void InitializeComponent() {{ }}
    }}
}}</Script>
</StiSerializer>
""")


def main():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = build_report()
    with open(OUTPUT_PATH, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(content)
    print(f'report saved: {OUTPUT_PATH} ({len(content)} bytes)')


if __name__ == '__main__':
    main()
