// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Reflection;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using static WuicCore.Server.Database.DynamicContext;
using WuicCore.Interfaces;
using Microsoft.EntityFrameworkCore.Infrastructure;
using WEB_UI_CRAFTER.Helpers;
using WuicOData.Services;

namespace WuicCore.Server.Database;

public partial class DynamicContext : DbContext
{
    static string _version;
    public static void SetContextVersion(string version) => _version = version;
    public static string GetContextVersion() => _version;

    private readonly DynamicModelService _dynamicModelService;

    public DynamicContext(DbContextOptions<DynamicContext> options, DynamicModelService dynamicModelService = null)
        : base(options)
    {
        _dynamicModelService = dynamicModelService;
    }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_100_CI_AS");

        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

        // Dynamic models generated at runtime from metadata tables
        var generatedAssembly = _dynamicModelService?.CurrentAssembly;
        if (generatedAssembly != null)
            modelBuilder.ApplyConfigurationsFromAssembly(generatedAssembly);

        OnModelCreatingPartial(modelBuilder);
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.ReplaceService<IModelCacheKeyFactory, CustomModelCacheKeyFactory>();
        base.OnConfiguring(optionsBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
