import { ChangeDetectorRef } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { BehaviorSubject } from 'rxjs';
import { MetadatiColonna } from '../../class/metadati_colonna';
import { MetaInfo } from '../../class/metaInfo';
import { TranslationManagerService } from '../../service/translation-manager.service';
import { DataSourceComponent } from '../data-source/data-source.component';
import { DynamicGenericTemplateComponent } from '../dynamic-generic-template/dynamic-generic-template.component';
import { IBindable } from '../../class/IBindable';
import { IDesigner } from '../../class/IDesigner';
import { CarouselOptions } from '../../class/carouselOptions';
import { UserInfoService } from '../../service/user-info.service';
import { ActivatedRoute } from '@angular/router';
import * as i0 from "@angular/core";
export declare class CarouselListComponent implements IBindable, IDesigner<CarouselOptions> {
    private titleService;
    private cd;
    private route;
    private trslSrv;
    private userInfo;
    hardcodedRoute: string;
    parentRecord: any;
    parentMetaInfo: MetaInfo;
    datasource: BehaviorSubject<DataSourceComponent>;
    hardcodedDatasource: DataSourceComponent;
    archetypeOptions: CarouselOptions;
    metaInfo: MetaInfo;
    data: any[];
    itemTemplateString: string;
    itemTemplate: typeof DynamicGenericTemplateComponent;
    titleField: string;
    imageColumn: MetadatiColonna | undefined;
    showConfigDialog: boolean;
    pageSizeMax: number;
    imageFieldCandidates: MetadatiColonna[];
    descriptionFieldCandidates: MetadatiColonna[];
    configDraft: {
        imageFieldName: string;
        descriptionFieldName: string;
        imageWidth: number;
        pageSize: number;
        itemTemplateString: string;
        numVisible: number;
        numScroll: number;
        usePreview: boolean;
    };
    routeName: any;
    constructor(titleService: Title, cd: ChangeDetectorRef, route: ActivatedRoute, trslSrv: TranslationManagerService, userInfo: UserInfoService);
    get isAdmin(): boolean;
    ngOnInit(): void;
    subscribeToDS(): void;
    parseData(dato: any[]): any[];
    openConfigDialog(): void;
    applyConfig(nextConfig?: any): void;
    saveCarouselMetadataPropsBag(): Promise<void>;
    onPageSizeSlideEnd(event: any): void;
    suggestItemTemplate(): void;
    applyPageSizeChange(value?: number): void;
    private syncConfigDraftFromOptions;
    private syncArchetypeOptionsFromPropsBag;
    private getCarouselPropsFromPropsBag;
    private ensureMergedExtraProps;
    private loadCurrentTableMetadataRecord;
    static ɵfac: i0.ɵɵFactoryDeclaration<CarouselListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CarouselListComponent, "wuic-carousel-list", never, { "hardcodedRoute": { "alias": "hardcodedRoute"; "required": false; }; "parentRecord": { "alias": "parentRecord"; "required": false; }; "parentMetaInfo": { "alias": "parentMetaInfo"; "required": false; }; "datasource": { "alias": "datasource"; "required": false; }; "hardcodedDatasource": { "alias": "hardcodedDatasource"; "required": false; }; }, {}, never, never, true, never>;
}
//# sourceMappingURL=carousel-list.component.d.ts.map