import { ChangeDetectorRef, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { BehaviorSubject } from 'rxjs';
import { MetadatiColonna } from '../../class/metadati_colonna';
import { MetaInfo } from '../../class/metaInfo';
import { TranslationManagerService } from '../../service/translation-manager.service';
import { DataSourceComponent } from '../data-source/data-source.component';
import { DynamicGenericTemplateComponent } from '../dynamic-generic-template/dynamic-generic-template.component';
import { UIChart } from 'primeng/chart';
import { ResultInfo } from '../../class/resultInfo';
import { UserInfoService } from '../../service/user-info.service';
import { ActivatedRoute } from '@angular/router';
import * as i0 from "@angular/core";
export declare class ChartListComponent implements OnInit, OnDestroy {
    private titleService;
    private cd;
    private route;
    private trslSrv;
    private userInfo;
    hardcodedRoute: string;
    parentRecord: any;
    parentMetaInfo: MetaInfo;
    datasource: BehaviorSubject<DataSourceComponent>;
    hardcodedDatasource: DataSourceComponent;
    chartRef?: UIChart;
    chartHostRef?: ElementRef<HTMLElement>;
    chartOptions: any;
    records: any[];
    private readonly contentRenderers;
    metas: MetadatiColonna[];
    cols: any;
    metaInfo: MetaInfo;
    loading: boolean;
    titleField: string;
    itemTemplateString: string;
    counter: number;
    itemTemplate: typeof DynamicGenericTemplateComponent;
    titleFunction: Function;
    basicData: any;
    basicOptions: any;
    data: any;
    totalRecords: number;
    cutoffValue: number;
    lastResultInfo?: ResultInfo;
    showConfigPopup: boolean;
    chartTypes: string[];
    selectedChartType: string;
    legendPositions: string[];
    animationEasings: string[];
    palettePresets: string[];
    ui: {
        legendDisplay: boolean;
        legendPosition: string;
        titleDisplay: boolean;
        titleText: string;
        tooltipEnabled: boolean;
        maintainAspectRatio: boolean;
        animationDuration: number;
        animationEasing: string;
        sortEnabled: boolean;
        sortDir: "asc" | "desc";
        stacked: boolean;
        indexAxis: "x" | "y";
        showGridX: boolean;
        showGridY: boolean;
        beginAtZero: boolean;
        tension: number;
        barThickness: number;
        cutout: number;
        palette: string;
    };
    private hasUserChartTypeOverride;
    private readonly chartHostMinHeight;
    private readonly chartBottomPadding;
    private readonly chartResizePassDelaysMs;
    private readonly defaultChartOptions;
    private metaChartOptions;
    private themeObserver?;
    private chartResizeObserver?;
    private pendingChartResizeHandle?;
    private pendingChartMeasureTimeouts;
    routeName: any;
    chartHostHeightPx?: number;
    private readonly onWindowResize;
    private readonly onWindowScroll;
    constructor(titleService: Title, cd: ChangeDetectorRef, route: ActivatedRoute, trslSrv: TranslationManagerService, userInfo: UserInfoService);
    get isAdmin(): boolean;
    ngOnInit(): void;
    ngOnDestroy(): void;
    private subscribeToDS;
    private hasGroupingApplied;
    private getTotalForCutoff;
    drillDown($event: any): void;
    private getSeriesValue;
    private getLabelValue;
    onCutoffChanged(event: Event): void;
    onCutoffValueChanged(value: number): void;
    private applyCutoffValue;
    openConfigPopup(): void;
    closeConfigPopup(): void;
    exportChart(): void;
    onChartTypeChanged(): void;
    onWidgetOptionsChanged(): void;
    private refreshChartOptions;
    private buildWidgetChartOptions;
    private observeThemeClassChanges;
    private getThemeChartOptions;
    isCartesianChart(): boolean;
    isLineLikeChart(): boolean;
    isBarChart(): boolean;
    isDoughnutLikeChart(): boolean;
    private getPaletteColors;
    private applyDatasetAppearance;
    private deepMerge;
    private persistChartArchetypeOptions;
    saveChartMetadataPropsBag(): Promise<void>;
    private ensureMergedExtraProps;
    private syncChartConfigFromPropsBag;
    onArchetypeConfigApply(nextConfig: any): void;
    getChartConfigValue(): any;
    private getChartPropsFromPropsBag;
    private loadCurrentTableMetadataRecord;
    parseData(result: ResultInfo, runtimeCutOff?: number): any;
    private startChartResizeObserver;
    private scheduleChartResize;
    private updateChartHostHeight;
    private getLayoutViewportBottom;
    private scheduleChartResizePasses;
    private clearPendingChartMeasureTimeouts;
    private measureAndResizeChart;
    private attachLayoutListeners;
    private detachLayoutListeners;
    static ɵfac: i0.ɵɵFactoryDeclaration<ChartListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ChartListComponent, "wuic-chart-list", never, { "hardcodedRoute": { "alias": "hardcodedRoute"; "required": false; }; "parentRecord": { "alias": "parentRecord"; "required": false; }; "parentMetaInfo": { "alias": "parentMetaInfo"; "required": false; }; "datasource": { "alias": "datasource"; "required": false; }; "hardcodedDatasource": { "alias": "hardcodedDatasource"; "required": false; }; }, {}, never, never, true, never>;
}
//# sourceMappingURL=chart-list.component.d.ts.map