import { AfterViewInit, ChangeDetectorRef, OnInit } from '@angular/core';
import { MetadataProviderService } from '../../service/metadata-provider.service';
import { DataSourceComponent } from "../data-source/data-source.component";
import { Table, TableRowCollapseEvent, TableRowExpandEvent } from 'primeng/table';
import { MetadatiColonna } from '../../class/metadati_colonna';
import { MetaInfo } from '../../class/metaInfo';
import { DomSanitizer } from '@angular/platform-browser';
import { Location } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { ContextMenu } from 'primeng/contextmenu';
import { Title } from "@angular/platform-browser";
import { TranslationManagerService } from '../../service/translation-manager.service';
import { BehaviorSubject } from 'rxjs';
import { UserInfoService } from '../../service/user-info.service';
import { MenuItem } from 'primeng/api';
import * as i0 from "@angular/core";
interface ListGridSavedState {
    id: string;
    name: string;
    description: string;
    isDefault: boolean;
    createdAt: string;
    filterInfo: any;
    sortInfo: any[];
    pageInfo: {
        currentPage: number;
        pageSize: number;
    };
    columnWidths: {
        [field: string]: number;
    };
}
interface ReportVariableInput {
    name: string;
    alias: string;
    value: string;
    type?: string;
}
export declare class ListGridComponent implements AfterViewInit, OnInit {
    private metaSrv;
    private sanitizer;
    private route;
    private router;
    private location;
    private titleService;
    private trslSrv;
    private cd;
    userInfo: UserInfoService;
    private static readonly GRID_VIEW_STATES_SETTINGS_KEY;
    private static readonly GRID_COLUMN_LAYOUT_SETTINGS_KEY;
    hardcodedRoute: string;
    parentRecord: any;
    parentMetaInfo: MetaInfo;
    datasource: BehaviorSubject<DataSourceComponent>;
    hardcodedDatasource: DataSourceComponent;
    rowCustomSelect: (rowData: any, $event: any, dt: Table) => void;
    table: Table;
    columnCtxMenu: ContextMenu;
    metadataColumnsDatasource: DataSourceComponent;
    records: any[];
    cols: any[];
    metas: MetadatiColonna[];
    metaInfo: MetaInfo;
    routeName: string;
    actionName: string;
    totalRecords: number;
    pageSize: number;
    rowNumber: number;
    orderColumn: string;
    orderDir: 'asc' | 'desc';
    loading: BehaviorSubject<boolean>;
    pageIndex: number;
    globalFilterFields: string[];
    searchValue: string;
    rowTemplate: any;
    selectedItems: any[];
    expandedRows: {};
    aggregates: any[];
    private syncFilterInfoQueryTimer;
    private syncGridStateQueryTimer;
    private suppressGridStateUrlPush;
    private releaseGridStateUrlPushTimer;
    private navigationTriggeredByPopstate;
    private suppressNextPageOnlyQuerySync;
    clientSideCrudToggleBusy: boolean;
    private persistedColumnWidthsByRoute;
    private persistedColumnLayoutByRoute;
    private remoteColumnLayoutHydrationInFlight;
    private persistedGridStatesByRoute;
    private remoteGridStatesHydrationInFlight;
    currentRouteSavedStates: ListGridSavedState[];
    selectedSavedStateId: string;
    private applyingSavedState;
    readonly NEW_GRID_STATE_OPTION_ID = "__new__";
    saveGridStateDialogVisible: boolean;
    saveGridStateDialogSelectedId: string;
    saveGridStateDialogNewName: string;
    saveGridStateDialogSetAsDefault: boolean;
    saveStateMenuItems: MenuItem[];
    clearFiltersMenuItems: MenuItem[];
    columnContextMenuItems: MenuItem[];
    selectedColumnForContextMenu?: MetadatiColonna;
    availableReports: {
        path: string;
        name: string;
    }[];
    reportMenuItems: MenuItem[];
    tableActionMenuItems: MenuItem[];
    reportVariableDialogVisible: boolean;
    reportVariableDialogLoading: boolean;
    selectedReportNameForVariables: string;
    selectedReportVariables: ReportVariableInput[];
    columnLayoutDialogVisible: boolean;
    columnLayoutDraft: {
        field: string;
        header: string;
        visible: boolean;
    }[];
    private pendingPreferredStateAutoApply;
    width_defined: string;
    MetadatiColonna: typeof MetadatiColonna;
    constructor(metaSrv: MetadataProviderService, sanitizer: DomSanitizer, route: ActivatedRoute, router: Router, location: Location, titleService: Title, trslSrv: TranslationManagerService, cd: ChangeDetectorRef, userInfo: UserInfoService);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    private subscribeToDS;
    private getEffectiveGridRowTemplate;
    private buildDefaultGridRowTemplateWithColumnTemplates;
    private buildGridColumnTemplateSwitchCases;
    private isAngularCellMarkupTemplate;
    private normalizeGridCellTemplate;
    private syncTableFilterUiFromDatasource;
    parseData(data: any): any;
    private rebuildTableActionMenuItems;
    onColumnHeaderContextMenu(event: MouseEvent, col: any, menu: ContextMenu): void;
    private ensureMetadataColumnsDatasourceRoute;
    private ensureMetadataColumnsDatasourceSchema;
    private fetchMetadataColumnRecord;
    private openColumnMetadataEditor;
    private hideColumnByMetadata;
    private editColumnDisplayStrings;
    parseColumns(columns: MetadatiColonna[]): any[];
    onColumnResize(event: any): Promise<void>;
    onColumnReorder(event: any): Promise<void>;
    pageFilterChange(event: any): Promise<void>;
    clearFilter(table: Table): Promise<void>;
    resetGridState(table: Table): Promise<void>;
    getTgtVal(tgt: any): any;
    getAggregations(col: MetadatiColonna): any[];
    exportXls(): Promise<void>;
    refresh(): void;
    canToggleClientSideCrud(): boolean;
    isClientSideCrudActive(): boolean;
    toggleClientSideCrud(): Promise<void>;
    syncAndDisableClientSideCrud(): Promise<void>;
    discardLocalAndDisableClientSideCrud(): Promise<void>;
    addRecord(): void;
    expandAll(): void;
    collapseAll(): void;
    onRowExpand(event: TableRowExpandEvent): void;
    onRowCollapse(event: TableRowCollapseEvent): void;
    toggleRow(item: any, event: Event, dt: Table): void;
    rowSelect(item: any, event: any, dt: Table): void;
    clearColumnFilter(col: MetadatiColonna, fetch: boolean): void;
    hasActiveFilter(col: MetadatiColonna): boolean;
    showActionColumn(): boolean;
    private syncFilterInfoQueryString;
    private syncGridStateQueryString;
    private clearGridStateQueryString;
    private scheduleSyncFilterInfoQueryString;
    private scheduleSyncGridStateQueryString;
    private syncPageInfoQueryString;
    private syncSortInfoQueryString;
    private pushGridStateUrl;
    private areUrlsEquivalent;
    private normalizedQueryParams;
    private getRouteKey;
    private getCurrentRouteColumnWidths;
    private getCurrentRouteColumnLayout;
    openColumnLayoutDialog(): void;
    resetColumnLayoutDraftToMetadata(): void;
    resetColumnLayoutDraftAndWidths(): Promise<void>;
    moveColumnLayoutDraft(index: number, direction: -1 | 1): void;
    saveColumnLayoutFromDialog(): Promise<void>;
    private extractVisibleColumnOrderFromReorderEvent;
    private applyPersistedColumnOrder;
    private persistCurrentRouteColumnLayoutFromCols;
    private loadPersistedColumnLayoutFromLocalStorage;
    private hydratePersistedColumnLayoutFromServerIfNeeded;
    private captureResizedColumnWidth;
    private captureAllColumnWidthsFromTableDom;
    private getFieldFromResizeEvent;
    private getWidthFromResizeEvent;
    private persistCurrentRouteColumnWidths;
    resetCurrentRouteColumnWidths(): Promise<void>;
    openSaveGridStateDialog(): void;
    onSaveGridStateDialogSelectionChange(): void;
    private updateSaveGridStateDialogSetAsDefault;
    saveCurrentRouteGridState(): Promise<void>;
    applySelectedGridState(stateId?: string): Promise<void>;
    removeSelectedGridState(): Promise<void>;
    onSelectedGridStateChange(stateId: string): Promise<void>;
    onSavedStateDropdownChange(event: Event): Promise<void>;
    setSelectedGridStateAsPreferred(): Promise<void>;
    private normalizePersistedColumnWidthMap;
    private normalizePersistedColumnLayoutMap;
    private loadPersistedGridStatesFromLocalStorage;
    private hydratePersistedGridStatesFromServerIfNeeded;
    private refreshCurrentRouteSavedStates;
    private tryAutoApplyPreferredStateForCurrentRoute;
    private hasExplicitGridStateInQueryParams;
    private persistGridStatesSettings;
    private deepClone;
    private syncSelectedSavedStateWithDatasourceCurrentState;
    private getCurrentGridStateSignatureFromDatasource;
    private getCurrentGridStateSignatureFromQueryOrDatasource;
    private getSavedStateSignature;
    private normalizeForCompare;
    private getCurrentGridStateFromQueryParams;
    private tryParseJson;
    private normalizeFilterInfoForCompare;
    private normalizeSortInfoForCompare;
    private applySavedFilterInfoToDatasourceDescriptor;
    private forceApplyPersistedColumnWidthsToTableDom;
    private getLeadingStructuralColumnCount;
    private debugColumnWidths;
    private buildNewReportName;
    private openReportDesigner;
    private openReportViewer;
    private buildReportParametersQueryString;
    openReportFromMenu(reportName: string): Promise<void>;
    cancelReportVariableDialog(): void;
    applyReportVariablesAndOpenViewer(): void;
    private loadReportList;
    static ɵfac: i0.ɵɵFactoryDeclaration<ListGridComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ListGridComponent, "wuic-list-grid", never, { "hardcodedRoute": { "alias": "hardcodedRoute"; "required": false; }; "parentRecord": { "alias": "parentRecord"; "required": false; }; "parentMetaInfo": { "alias": "parentMetaInfo"; "required": false; }; "datasource": { "alias": "datasource"; "required": false; }; "hardcodedDatasource": { "alias": "hardcodedDatasource"; "required": false; }; "rowCustomSelect": { "alias": "rowCustomSelect"; "required": false; }; }, {}, never, never, true, never>;
}
export {};
//# sourceMappingURL=list-grid.component.d.ts.map