import { AfterViewInit, OnDestroy, OnInit } from '@angular/core';
import { MenuItem } from 'primeng/api';
import { DataSourceComponent } from '../data-source/data-source.component';
import { MetaInfo } from '../../class/metaInfo';
import { EditFormComponent } from '../edit-form/edit-form.component';
import { TranslationManagerService } from '../../service/translation-manager.service';
import { BehaviorSubject } from 'rxjs';
import { MetadataProviderService } from '../../service/metadata-provider.service';
import { Router } from '@angular/router';
import { UserInfoService } from '../../service/user-info.service';
import * as i0 from "@angular/core";
export declare class MetadataEditorComponent implements AfterViewInit, OnInit, OnDestroy {
    private trslSrv;
    private metaSrv;
    private router;
    private userInfoSrv;
    datasource: BehaviorSubject<DataSourceComponent>;
    hardcodedDatasource: DataSourceComponent;
    saveCallback: Function;
    hideReports: boolean;
    hideRelatedTableActions: boolean;
    hideRelatedColumnActions: boolean;
    datasourceTabelle: DataSourceComponent;
    datasourceColonne: DataSourceComponent;
    datasourceRelatedMetadataCustomActions: DataSourceComponent;
    datasourceRelatedMetadataAuthTable: DataSourceComponent;
    datasourceRelatedMetadataAuthColumn: DataSourceComponent;
    datasourceRelatedMetadataTableStyles: DataSourceComponent;
    datasourceRelatedMetadataColumnStyles: DataSourceComponent;
    items: MenuItem[] | undefined;
    metaInfo: MetaInfo;
    ref: import("primeng/dynamicdialog").DynamicDialogRef<EditFormComponent>;
    readonly metaCustomActionsRoute: any;
    readonly metaAuthTableRoute: any;
    readonly metaAuthColumnRoute: any;
    readonly metaTableStyleRoute: any;
    readonly metaColumnStyleRoute: any;
    private fetchInfoSub?;
    private translationsSub?;
    private viewReady;
    private extendedMenuRefreshSeq;
    private reportMenuRefreshSeq;
    private roleDescriptionById;
    constructor(trslSrv: TranslationManagerService, metaSrv: MetadataProviderService, router: Router, userInfoSrv: UserInfoService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    private unwrapMenuItem;
    isDeletableMenuItem(item: any): boolean;
    onMenuItemClick(event: Event, item: any): void;
    onMenuItemDeleteClick(event: Event, item: any): Promise<void>;
    private subscribeToDS;
    private rebuildMenuItems;
    private t;
    private buildNewReportName;
    private getCurrentRouteName;
    private openReportDesigner;
    private refreshReportMenuItems;
    private refreshExtendedMetadataMenuItems;
    private toMenuItems;
    private getEditorStrategies;
    private getRelatedMetadataDatasource;
    private getEditorStrategyByKey;
    private hydrateContextRecordFromSection;
    private resolveEditorContext;
    private deleteRelatedMetadataItem;
    private normalizeRecordForDelete;
    private deepUnwrapModelValue;
    private appendRelatedMetadataSection;
    private pickFirstDefined;
    private formatTableAuthorizationLabel;
    private formatAuthorizationPermissions;
    private formatColumnAuthorizationLabel;
    private formatColumnAuthorizationPermissions;
    private formatTableStyleLabel;
    private toTriStateFlag;
    private toBool;
    private normalizeKey;
    private unwrapValue;
    private getUserDescription;
    private getRoleDescription;
    private hydrateRoleDescriptionCache;
    private hydrateRoleDescriptionsFromLookupRoutes;
    private isRoleLookupField;
    private extractLookupItems;
    private pickLookupValue;
    private pickLookupText;
    private hasMeaningfulRoleText;
    private selectRelevantColumnAuthorizations;
    private selectRelevantTableAuthorizations;
    private shouldShowAllAuthorizationsForMetadataEditor;
    private getNestedTableAuthorizations;
    private getNestedTableStyles;
    private getNestedColumnStyles;
    private getNestedColumnAuthorizations;
    private getNestedRelationArray;
    private computeAuthorizationScore;
    private ensureDatasourceRoute;
    private ensureDatasourceSchema;
    private reloadMetadataEditorState;
    private getEditorKeyFromRoute;
    private openEditDialog;
    private publishDatasourceState;
    private resolveLocalEditorContext;
    private openInsertRelatedMetadata;
    private applyCurrentRouteColumnLookupFilter;
    private openInsertColumnEditor;
    private openInsertColumnActionMetadata;
    private parseCreatedColumnId;
    private getAddColumnEndpoint;
    private syncMetadataFromSchema;
    private getConnectionInfo;
    private parseMaybeSerialized;
    private getAsmxEndpoint;
    private removeColumn;
    private invalidateMetadataCaches;
    openEditor(item: any): Promise<void>;
    static ɵfac: i0.ɵɵFactoryDeclaration<MetadataEditorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MetadataEditorComponent, "wuic-metadata-editor", never, { "datasource": { "alias": "datasource"; "required": false; }; "hardcodedDatasource": { "alias": "hardcodedDatasource"; "required": false; }; "saveCallback": { "alias": "saveCallback"; "required": false; }; "hideReports": { "alias": "hideReports"; "required": false; }; "hideRelatedTableActions": { "alias": "hideRelatedTableActions"; "required": false; }; "hideRelatedColumnActions": { "alias": "hideRelatedColumnActions"; "required": false; }; }, {}, never, never, true, never>;
}
//# sourceMappingURL=metadata-editor.component.d.ts.map