import { WtoolboxService } from "../service/wtoolbox.service";
import { MetadatiTabella } from "./metadati_tabella";
import { MetadatiUiStiliColonna } from "./metadati_ui_stili_colonna";
import { MetadatiUtentiAutorizzazioniColonna } from "./metadati_utenti_autorizzazioni_colonna";
import { MetaInfo } from "./metaInfo";
import { ValidationRule } from "./validationRule";
import type { IFieldEditor } from "./IFieldEditor";
import { BehaviorSubject } from "rxjs";
import { EditorOptions } from "../component/code-editor/editor-options";
export declare class MetadatiColonna {
    __user_id: number;
    mc_id: number;
    mc_real_column_name: string;
    mc_nome_colonna: string;
    ang_name: string;
    mc_db_column_type: string;
    mc_is_primary_key: boolean;
    mc_ui_size_width: string;
    mc_ui_size_height: string;
    mc_display_string_in_edit: string;
    mc_display_string_in_view: string;
    mc_ui_column_type: 'text' | 'txt_area' | 'number' | 'number_boolean' | 'date' | 'datetime' | 'boolean' | 'lookupByID' | 'multiple_check' | 'point' | 'button' | 'code_editor' | 'dictionary' | 'dictionary_radio' | 'html_area' | 'upload' | 'color' | 'polygon' | 'tree' | string;
    mc_ordine: number;
    mc_hide_in_list: boolean;
    mc_hide_in_edit: boolean;
    mc_hide_in_detail: boolean;
    hide_in_import: boolean;
    mc_hide_in_service: boolean;
    mc_show_in_filters: boolean;
    mc_is_range_filter: boolean;
    mc_default_value: string;
    mc_is_multicheck_filter: boolean;
    mc_ui_grid_size_width: string;
    mc_is_db_computed: boolean;
    mc_logic_editable: boolean;
    mc_logic_nullable: boolean;
    mc_default_value_callback: string;
    mc_selection_changing_custom_function: string;
    mc_selection_changed_custom_function: string;
    mc_suggest_value_callback: string;
    mc_ui_grid_conditional_template_class: string;
    mc_ui_grid_conditional_alt_template_class: string;
    mc_ui_grid_conditional_template_condition: string;
    mc_ui_grid_column_data_template: string;
    mc_dictionary_value: string;
    mc_aggregation: string;
    mc_is_computed: boolean;
    mc_computed_formula: string;
    mc_computed_client_formula: string;
    convert_null_to_string: string;
    mc_max_length: string;
    mc_grant_by_default: boolean;
    mc_edit_associated_tab: string;
    mc_auto_uppercase: boolean;
    mc_is_logic_delete_key: boolean;
    mc_tooltip: string;
    mc_validation_has: boolean;
    mc_validation_required: boolean;
    mc_validation_message: string;
    mc_validation_type: string;
    mc_validation_pattern: string;
    mc_validation_max_length: string;
    mc_validation_min_length: string;
    mc_validation_pattern_message: string;
    mc_validation_max_length_message: string;
    mc_validation_min_length_message: string;
    mc_validation_type_message: string;
    mc_validation_custom_callback: string;
    mc_logic_converter_has: boolean;
    mc_logic_converter_read_callback: string;
    mc_logic_converter_write_callback: string;
    mc_default_sort: string;
    mc_default_multisort_order: number;
    mc_hide_in_export: boolean;
    mc_disable_sorting: boolean;
    mc_ui_is_password: boolean;
    mc_password_encription_method: string;
    mc_custom_join: string;
    mc_ui_lookup_filter: string;
    mc_ui_lookup_dataValueField: string;
    mc_ui_lookup_dataTextField: string;
    mc_ui_lookup_entity_name: string;
    mc_serverside_operations: boolean;
    mc_ui_pagesize: number;
    mc_ui_lookup_computed_dataTextField: string;
    mc_ui_lookup_combo_text_edit_computed_dataTextField: string;
    mc_logic_allow_navigation: boolean;
    mc_logic_navigate_new_window: boolean;
    mc_ui_lookup_edit_allow: boolean;
    mc_ui_lookup_insert_allow: boolean;
    mc_ui_lookup_search_grid: boolean;
    mc_custom_select_clause: string;
    mc_ui_slider_min?: number;
    mc_ui_slider_max?: number;
    mc_ui_slider_format: string;
    mc_ui_slider_decimals: number;
    mc_ui_slider_smallstep: number;
    mc_ui_slider_largestep: number;
    mc_ui_grid_is_multiple_check: boolean;
    mc_ui_grid_related_id_field: string;
    mc_ui_grid_display_field: string;
    mc_ui_grid_manytomany_route: string;
    mc_ui_grid_route: string;
    mc_ui_grid_manytomany_local_id_field: string;
    mc_ui_grid_manytomany_related_id_field: string;
    mc_ui_grid_local_id_field: string;
    isImageUpload: boolean;
    isDBUpload: boolean;
    upload_secure: boolean;
    isMultipleUpload: boolean;
    IsZippedUpload: boolean;
    UseRouteNameAsSubfolder: boolean;
    UseRecordIDAsSubfolder: boolean;
    key_field_name: string;
    DefaultUploadRootPath: string;
    MultipleUploadTableRoute: string;
    MultipleUploadBlobFieldName: string;
    MultipleUploadBlobThumbFieldName: string;
    MultipleUploadFilePathFieldName: string;
    MultipleUploadFileTitleFieldName: string;
    MultipleUploadFileNameFieldName: string;
    MultipleUploadFileSizeFieldName: string;
    MultipleUploadFileTypeFieldName: string;
    MultipleUploadFileIconPathFieldName: string;
    MultipleUploadFKey: string;
    AllowWebCamShot: boolean;
    AllowWebCamVideo: boolean;
    createThumb: boolean;
    thumbWidth: number;
    thumbHeight: number;
    customUploadHandlerPath: string;
    uploadsecure: boolean;
    mc_button_caption: string;
    mc_button_action: string;
    mc_button_confirm_message: string;
    mc_button_executed_message: string;
    mc_button_tooltip: string;
    mc_button_template: string;
    mc_button_image: string;
    mc_button_visibility_condition: string;
    mc_button_action_type: number;
    mc_logic_cascade_isMember: boolean;
    mc_logic_cascade_childToReset: string;
    mc_logic_cascade_filteringParent: string;
    mc_filter_disable_operator: string;
    mc_filter_hide_operator: boolean;
    mc_editable_insert_only: string;
    _Metadati_UI_Stili_Colonnes: MetadatiUiStiliColonna[];
    _Metadati_Utenti_Autorizzazioni_Colonnes: MetadatiUtentiAutorizzazioniColonna[];
    mc_custom_edit_cell_template: string;
    mc_filter_hierarchy: boolean;
    cssPaths: string;
    snippetsTemplate: string;
    container_class: string;
    useHtmlAspxEditor: boolean;
    allowed_file_types: string;
    max_file_size: number;
    mc_value_change_trigger_event: string;
    mc_syntax_builder: string;
    use_slider_in_edit: boolean;
    use_gauge_in_view: boolean;
    use_chart_in_view: boolean;
    hide_value_in_view: boolean;
    mc_chart_label_template: string;
    mc_chart_ranges: string;
    mc_chart_select: string;
    mc_props_bag: string;
    extras: {
        parameters: any[];
        form: {
            columns?: number;
            disabled?: boolean;
        };
        style: {
            editCss: string;
        };
        checkUniqueValue: string;
        lookup: any;
        customEditorConfig: {
            editorOptions: EditorOptions;
            compilerOptions?: monaco.languages.typescript.CompilerOptions;
            schemas?: any[];
            codeContext?: string;
            extraLibs?: string[];
            routeContextField?: string;
            columnContextField?: string;
        };
        uploader: {
            beforeUpload: string | Function;
        };
    };
    hideSelectAllCheck: boolean;
    jsonEditor: string;
    afterUpload: string;
    logic_disabled: boolean;
    _Metadati_Tabelle: MetadatiTabella;
    isOut: any;
    $$currentOperator?: {
        name: string;
        caption: string;
    };
    mc_ui_filter_size_width: string;
    validationsRules: ValidationRule[];
    extraFields: any;
    mc_button_action__fn: (record: {
        [key: string]: BehaviorSubject<any>;
    }, event: any, field: MetadatiColonna, wtoolbox: typeof WtoolboxService) => void;
    mc_selection_changed_custom_function__fn: (record: {
        [key: string]: BehaviorSubject<any>;
    }, field: MetadatiColonna, metaInfo: MetaInfo, newValue: any, oldValue: any, wtoolbox: typeof WtoolboxService, nestedIndex?: number, nodes?: any[]) => void;
    mc_selection_changing_custom_function__fn: (record: {
        [key: string]: BehaviorSubject<any>;
    }, field: MetadatiColonna, metaInfo: MetaInfo, newValue: any, oldValue: any, event: any, wtoolbox: typeof WtoolboxService) => void;
    mc_default_value_callback__fn: (record: {
        [key: string]: BehaviorSubject<any>;
    }, field: MetadatiColonna, metaInfo: MetaInfo, wtoolbox: typeof WtoolboxService) => any;
    mc_suggest_value_callback__fn: (record: {
        [key: string]: BehaviorSubject<any>;
    }, field: MetadatiColonna, metaInfo: MetaInfo, wtoolbox: typeof WtoolboxService) => string;
    mc_validation_custom_callback__fn: (record: {
        [key: string]: BehaviorSubject<any>;
    }, field: MetadatiColonna, vr: ValidationRule, wtoolbox: typeof WtoolboxService) => boolean;
    editor: BehaviorSubject<IFieldEditor>;
    codeEditing: boolean;
    propConstructor: any;
    propPath: string;
    constructor(name: string);
    static clone(col: MetadatiColonna): MetadatiColonna;
    static formatGridViewValue(metaColumn: MetadatiColonna, recordObj: any): any;
    private static evaluateGridColumnDataTemplate;
    static validateField(value: any, vr: ValidationRule, record: {
        [key: string]: BehaviorSubject<any>;
    }, field: MetadatiColonna): Promise<void>;
}
//# sourceMappingURL=metadati_colonna.d.ts.map