import { BehaviorSubject } from "rxjs";
import { DataSourceComponent } from "../component/data-source/data-source.component";
import { WtoolboxService } from "../service/wtoolbox.service";
import { MetadatiConditionGroup } from "./metadati_condition_group";
import { MetadatiCustomActionTabella } from "./metadati_custom_actions_tabelle";
import { MetadatiUiStiliTabella } from "./metadati_ui_stili_tabella";
import { MetaInfo } from "./metaInfo";
import { MapOptions } from "./mapOptions";
import { GroupInfo } from "./groupInfo";
import { AggregationInfo } from "./aggregationInfo";
import { SchedulerOptions } from "./schedulerOptions";
import { TreeOptions } from "./treeOptions";
import { CarouselOptions } from "./carouselOptions";
import { ChartOptions } from "./chartOptions";
import { FormOptions } from "./formOptions";
export declare class MetadatiTabella {
    __user_id: number;
    ProjectMetadataVersion: number;
    md_id: number;
    md_nome_tabella: string;
    md_editable: boolean;
    md_deletable: boolean;
    md_insertable: boolean;
    md_display_string: string;
    md_long_description: string;
    is_system_route: boolean;
    md_url_read: string;
    md_url_update: string;
    md_url_delete: string;
    md_url_insert: string;
    md_sortable: boolean;
    md_groupable: boolean;
    md_scrollable: boolean;
    md_pageable: boolean;
    md_pagesize: number;
    md_edit_popup: boolean;
    md_inline_edit: boolean;
    md_server_side_operations: boolean;
    md_nested_grid_routes: string;
    md_detail_grid_routes: string;
    md_parent_key_name: string;
    md_master_detail_edit: boolean;
    md_default_filter: string;
    md_header_rows_edit: boolean;
    md_multiple_selection: boolean;
    md_detail_action: boolean;
    md_display_formula: null;
    md_importable: boolean;
    md_clonable: boolean;
    md_open_filter_onload: boolean;
    md_before_save: null;
    md_after_save: null;
    md_after_load: null;
    md_ui_grid_conditional_template: string;
    md_ui_grid_conditional_alt_template: string;
    md_ui_grid_conditional_template_condition: string;
    md_conditional_update_rule: null;
    md_conditional_delete_rule: null;
    md_appoggio_left_table: null;
    md_appoggio_right_table: null;
    md_appoggio_allow_drag_drop: null;
    md_appoggio_edit_extra_data: null;
    md_appoggio_left_fk_name: null;
    md_appoggio_right_fk_name: null;
    md_treeview_template: string;
    md_gridview_template: string;
    md_rowTemplate: string;
    md_filter_template: string;
    md_detail_template: string;
    md_edit_template: string;
    md_book_html_template: string;
    md_gallery_html_template: string;
    md_map_html_template: string;
    md_grant_by_default: boolean;
    md_record_restriction_key_user_field_list: string;
    md_user_id_field_name: string;
    md_logging_enable: boolean;
    md_logging_last_mod_user_field_name: string;
    md_logging_last_mod_date_field_name: string;
    md_logging_insert_user_field_name: string;
    md_logging_insert_date_field_name: string;
    md_logging_delete_user_field_name: string;
    md_loggingdelete_date_field_name: string;
    md_logging_azienda_field_name: string;
    md_has_logic_delete: boolean;
    md_disabilita_filtri: boolean;
    md_grid_scroll_height: string;
    md_table_edit: boolean;
    md_tab_edit: boolean;
    md_table_column_counta: null;
    md_show_record_count: boolean;
    md_page_size_choice: string;
    md_is_reticular: boolean;
    reticular_key_name: string;
    reticular_key_value: null;
    md_conn_name: string;
    md_db_name: string;
    md_primary_key_type: string;
    md_schema_name: string;
    md_route_name: string;
    md_is_view: boolean;
    md_expose_in_webapi: boolean;
    md_expose_in_wcf: boolean;
    md_include_definition: boolean;
    md_service_custom_settings: boolean;
    md_service_page_size: number;
    md_service_disable_sorting: boolean;
    md_service_disable_filtering: boolean;
    md_service_enable_edit: boolean;
    md_service_enable_insert: boolean;
    md_service_enable_delete: boolean;
    md_service_enable_detail: boolean;
    md_service_enable_clone: boolean;
    md_service_apply_default_filter: boolean;
    md_service_enable_logging: boolean;
    md_allow_drag: boolean;
    md_allow_drop: boolean;
    md_drop_callback: null;
    md_custom_row_template: null;
    md_custom_repeater_view_template: null;
    md_custom_filter_template: null;
    md_custom_filter_cell_template: null;
    md_custom_view_cell_template: null;
    md_custom_edit_cell_template: null;
    md_custom_pager_template: null;
    md_custom_header_template: null;
    md_custom_header_cell_template: null;
    md_custom_command_header_template: null;
    md_custom_title_template: null;
    md_hide_refresh: null;
    md_hide_print: null;
    md_hide_export_pdf: null;
    md_hide_export_xls: null;
    md_auto_refresh_seconds: null;
    md_inline_cell_editing: boolean;
    md_batch_save: boolean;
    md_props_bag: null;
    md_hide_select_all_check: boolean;
    md_multiple_radio_selection: boolean;
    md_persist_row_selection_accross_paging: boolean;
    md_custom_edit: null;
    md_custom_delete: null;
    md_delete_and_sync: boolean;
    hide_toolbar: boolean;
    preventNavigateOnFilter: boolean | undefined;
    extraProps: {
        endpoint: {
            type: string;
            method: 'get' | 'post';
            uri: string;
            parameterMapping: [
                {
                    source: {
                        type: string;
                        name: string;
                        required: boolean;
                        path: string;
                    };
                    target: {
                        type: string;
                        name: string;
                        parseFunction: string;
                    };
                }
            ];
        };
        cascadeDefinition: any;
        archetypes: {
            scheduler: SchedulerOptions;
            tree: TreeOptions;
            spreadsheet: any;
            list: any;
            map: MapOptions;
            excel: any;
            carousel: CarouselOptions;
            chart: ChartOptions;
            form: FormOptions;
        };
        parameters: any[];
        groupInfo: GroupInfo[];
        aggregates: AggregationInfo[];
        cloneDefinition: {
            relatedRoutes: {
                relatedRoute: string;
                relatedIdField: string;
            }[];
        };
        changeTracking: boolean;
        client_side_crud: boolean | {
            enabled?: boolean;
            batchSize?: number;
            maxPages?: number;
            includeLookupRoutes?: boolean;
        };
    };
    parameterInfo: any[];
    md_update_uri: string;
    hideSave: any;
    hideRollback: any;
    hideGoBack: any;
    _Metadati_Custom_Actions_Tabelles: MetadatiCustomActionTabella[];
    _Metadati_Utenti_Autorizzazioni_Tabelles: any[];
    _Metadati_UI_Stili_Tabelles: MetadatiUiStiliTabella[];
    _Metadati_Condition_Groups: MetadatiConditionGroup[];
    md_conditional_update_rule_fn: (metaInfo: MetaInfo, record: any, datasource: DataSourceComponent, wtoolbox: typeof WtoolboxService) => boolean;
    md_conditional_delete_rule_fn: (metaInfo: MetaInfo, record: any, datasource: DataSourceComponent, wtoolbox: typeof WtoolboxService) => boolean;
    md_before_save_fn: (datasource: DataSourceComponent, savingData: any, beforeSync: (shouldSync: boolean) => void, event: any, wtoolbox: typeof WtoolboxService) => Promise<any> | any;
    md_after_save_fn: (datasource: DataSourceComponent, savingData: any, syncedData: any, isInsert: boolean, isClone: boolean, isDelete: boolean, event: any, wtoolbox: typeof WtoolboxService) => Promise<void> | void;
    md_after_load_fn: (datasource: DataSourceComponent, originalEvent: any, result: any, loadedRecords: any[], isInsert: boolean, wtoolbox: typeof WtoolboxService) => Promise<void> | void;
    md_display_formula_fn: (metaInfo: MetaInfo, record: {
        [key: string]: BehaviorSubject<any>;
    }, datasource: DataSourceComponent, wtoolbox: typeof WtoolboxService) => string;
    constructor(name: string);
}
//# sourceMappingURL=metadati_tabella.d.ts.map