import { KeyValue } from '@angular/common';
import { ChangeDetectorRef, OnChanges } from '@angular/core';
import { ClassicPreset as Classic } from 'rete';
import * as i0 from "@angular/core";
type NodeExtraData = {
    width?: number;
    height?: number;
    [key: string]: any;
};
type SortValue<N extends Classic.Node> = (N['controls'] | N['inputs'] | N['outputs'])[string];
export declare class WorkflowDesignerNodeComponent implements OnChanges {
    private cdr;
    data: Classic.Node & NodeExtraData;
    emit: (data: any) => void;
    rendered: () => void;
    seed: number;
    get width(): number;
    get height(): number;
    get selected(): boolean;
    get nodeType(): string;
    get actionScope(): string;
    get actionType(): string;
    get accentColor(): string;
    get backgroundColor(): string;
    constructor(cdr: ChangeDetectorRef);
    ngOnChanges(): void;
    sortByIndex<N extends Classic.Node, I extends KeyValue<string, SortValue<N>>>(a: I, b: I): number;
    get shapePath(): string;
    get shapeKind(): string;
    get svgViewBox(): string;
    get titleBandX(): number;
    get titleBandWidth(): number;
    get titleTextX(): number;
    get titleBandHeight(): number;
    get titleTextY(): number;
    get titleLineDy(): number;
    get titleLines(): string[];
    get dashedStroke(): string | null;
    private resolveVisual;
    private get effectiveWidth();
    private get effectiveHeight();
    private resolveShape;
    private roundedRectPath;
    private polygonPath;
    private wrapLabel;
    private truncateWithEllipsis;
    static ɵfac: i0.ɵɵFactoryDeclaration<WorkflowDesignerNodeComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<WorkflowDesignerNodeComponent, "wuic-workflow-designer-node", never, { "data": { "alias": "data"; "required": false; }; "emit": { "alias": "emit"; "required": false; }; "rendered": { "alias": "rendered"; "required": false; }; }, {}, never, never, true, never>;
}
export {};
//# sourceMappingURL=workflow-designer-node.component.d.ts.map