import { HttpClient } from '@angular/common/http';
import { OnInit, AfterViewInit, OnDestroy } from '@angular/core';
import { MonacoEditorComponent, MonacoEditorLoaderService } from '@materia-ui/ngx-monaco-editor';
import { BehaviorSubject } from 'rxjs';
import { SqlProvider } from './sql-parser';
import { MetadatiColonna } from '../../class/metadati_colonna';
import { EditorOptions } from './editor-options';
import { MetaInfo } from '../../class/metaInfo';
import { WtoolboxService } from '../../service/wtoolbox.service';
import { MetadataProviderService } from '../../service/metadata-provider.service';
import { UserInfoService } from '../../service/user-info.service';
import { TSProvider } from './ts-parser';
import { DataProviderService } from '../../service/data-provider.service';
import * as i0 from "@angular/core";
export declare class CodeEditorComponent implements OnInit, AfterViewInit, OnDestroy {
    private monacoLoaderService;
    private http;
    private metaSrv;
    private userInfo;
    private dataSrv;
    private wtoolbox;
    style: string;
    contextMenuAnchor: any;
    field: MetadatiColonna;
    record?: {
        [key: string]: BehaviorSubject<any>;
    };
    metaInfo: MetaInfo;
    editorRef: MonacoEditorComponent | undefined;
    editor: monaco.editor.IStandaloneCodeEditor | undefined;
    ctxs: any;
    editorOptions: EditorOptions;
    editorModelValue: string;
    sampleCode: string;
    fullscreen: boolean;
    render: boolean;
    treeNodes: any[];
    primeTreeNodes: any[];
    sqlObjView: boolean;
    sqlProvider: SqlProvider | undefined;
    errors: {
        Message: string;
    }[];
    codeContext: string;
    tsProvider: TSProvider;
    private layoutRaf;
    private scrollHosts;
    private readonly onHostScroll;
    private recordValueSub;
    private syncingFromRecord;
    constructor(monacoLoaderService: MonacoEditorLoaderService, http: HttpClient, metaSrv: MetadataProviderService, userInfo: UserInfoService, dataSrv: DataProviderService, wtoolbox: WtoolboxService);
    setFullScreen($event: any, ctx: any): void;
    toggleSqlObjView($event: any, ctx: any): void;
    onContentChange($event: any): void;
    onTreeNodeDragStart(event: DragEvent, dataItem: any): void;
    onTreeNodeDragEnd(event: DragEvent, dataItem: any): void;
    testSql($event: any, ctx: any): Promise<void>;
    suggest($event: any, ctx: any): Promise<void>;
    onEditorModelChange(value: string): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    private scheduleEditorLayout;
    private getScrollableAncestors;
    private bindRecordValue;
    private mapToPrimeTreeNodes;
    static ɵfac: i0.ɵɵFactoryDeclaration<CodeEditorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CodeEditorComponent, "wuic-code-editor", never, { "field": { "alias": "field"; "required": false; }; "record": { "alias": "record"; "required": false; }; "metaInfo": { "alias": "metaInfo"; "required": false; }; }, {}, never, never, true, never>;
}
//# sourceMappingURL=code-editor.component.d.ts.map