import { ChangeDetectorRef, ElementRef, OnInit, QueryList } from '@angular/core';
import { GoogleMap, MapInfoWindow, MapPolygon } from "@angular/google-maps";
import { MarkerClusterer } from "@googlemaps/markerclusterer";
import { MetaInfo } from '../../class/metaInfo';
import { DataSourceComponent } from '../data-source/data-source.component';
import { BehaviorSubject } from 'rxjs';
import { Title } from '@angular/platform-browser';
import { MapOptions, Point } from '../../class/mapOptions';
import { MetadatiColonna } from '../../class/metadati_colonna';
import { DynamicGenericTemplateComponent } from '../dynamic-generic-template/dynamic-generic-template.component';
import { IBindable } from '../../class/IBindable';
import { IDesigner } from '../../class/IDesigner';
import { UserInfoService } from '../../service/user-info.service';
import { TranslationManagerService } from '../../service/translation-manager.service';
import { ActivatedRoute } from '@angular/router';
import * as i0 from "@angular/core";
export declare class MapListComponent implements OnInit, IBindable, IDesigner<MapOptions> {
    private titleService;
    private cd;
    private route;
    private userInfo;
    private trslSrv;
    map: GoogleMap;
    info: MapInfoWindow;
    markerElements: QueryList<any>;
    mapHostRef?: ElementRef<HTMLElement>;
    MAP_LIB: google.maps.MapsLibrary;
    MARKER_LIB: google.maps.MarkerLibrary;
    PLACE_LIB: google.maps.PlacesLibrary;
    DRAWING_LIB: google.maps.DrawingLibrary;
    hardcodedRoute: string;
    parentRecord: any;
    parentMetaInfo: MetaInfo;
    datasource: BehaviorSubject<DataSourceComponent>;
    hardcodedDatasource: DataSourceComponent;
    metaInfo: MetaInfo;
    archetypeOptions: MapOptions;
    data: any[];
    itemTemplateString: string;
    itemTemplate: typeof DynamicGenericTemplateComponent;
    center: Point;
    markers: any[];
    vertexArray: {
        lat: number;
        lng: number;
    }[][];
    circles: {
        center: {
            lat: number;
            lng: number;
        };
        radius: number;
    }[];
    infoContent: string;
    zoom: number;
    parser: DOMParser;
    dragging: boolean;
    mc: MarkerClusterer;
    loading: boolean;
    bounds: google.maps.LatLngBounds;
    currentMarker: any;
    showConfigDialog: boolean;
    fieldCandidates: MetadatiColonna[];
    initCompleted: boolean;
    private fetchInfoSubscription?;
    private destroyed;
    routeName: string;
    mapHostHeightPx?: number;
    private mapResizeObserver?;
    private pendingMapResizeHandle?;
    private pendingMapMeasureTimeouts;
    private readonly mapHostMinHeight;
    private readonly mapBottomPadding;
    private readonly mapResizePassDelaysMs;
    polygonEditMode: boolean;
    private polygonSaveInProgress;
    private editedPolygonKeys;
    private readonly onWindowResize;
    private readonly onWindowScroll;
    constructor(titleService: Title, cd: ChangeDetectorRef, route: ActivatedRoute, userInfo: UserInfoService, trslSrv: TranslationManagerService);
    get isAdmin(): boolean;
    ngOnInit(): Promise<void>;
    ngOnDestroy(): void;
    subscribeToDS(): Promise<void>;
    boundsToPolyline(bounds: google.maps.LatLngBounds): string;
    parseData(data: any): any;
    getMarkerContent(record: any): any;
    getCurrentPositionAsync(): Promise<GeolocationPosition>;
    initMap(metaInfo: MetaInfo): Promise<void>;
    openMapConfig(): void;
    applyMapConfig(nextConfig?: any): Promise<void>;
    saveMapMetadataPropsBag(): Promise<void>;
    private syncArchetypeOptionsFromPropsBag;
    private getMapPropsFromPropsBag;
    private loadCurrentTableMetadataRecord;
    private ensureMergedExtraProps;
    private syncMapViewportFromMeta;
    debounce(callback: any, waitTime: any): (...args: any[]) => void;
    filterByBoundaries(): void;
    zoomIn(): void;
    zoomOut(): void;
    logCenter(): void;
    hello($event: any): void;
    addMarkerOnClick(event: any): void;
    mapDragstart(markerElem: any, marker: any, $event: any): void;
    mapDragend(markerElem: any, marker: any, $event: any): Promise<void>;
    testMarker(): void;
    setAllDraggable(): void;
    hasPolygonField(): boolean;
    showMarkerDragButton(): boolean;
    showPolygonEditButton(): boolean;
    togglePolygonEditing(): Promise<void>;
    onPolygonShapeChanged(polygonElem: MapPolygon, record: any, polygonIndex: number): void;
    openInfo(markerElem: any, marker: any): void;
    renderMarkerInfo(selectedMarker: any): any;
    private getRecordFieldValue;
    private getPolygonMetadataColumn;
    private setPolygonEditability;
    private getVerticesFromMapPolygon;
    private verticesToPolygonWkt;
    private getPolygonEditKey;
    private saveEditedPolygons;
    private getPointMetadataColumn;
    private updateMarkerRecordPositionInMemory;
    private saveDraggedMarkerPosition;
    private startMapResizeObserver;
    private scheduleMapResizePasses;
    private measureAndResizeMap;
    private scheduleMapResize;
    private updateMapHostHeight;
    private getLayoutViewportBottom;
    private clearPendingMapMeasureTimeouts;
    private attachLayoutListeners;
    private detachLayoutListeners;
    static ɵfac: i0.ɵɵFactoryDeclaration<MapListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MapListComponent, "wuic-map-list", never, { "hardcodedRoute": { "alias": "hardcodedRoute"; "required": false; }; "parentRecord": { "alias": "parentRecord"; "required": false; }; "parentMetaInfo": { "alias": "parentMetaInfo"; "required": false; }; "datasource": { "alias": "datasource"; "required": false; }; "hardcodedDatasource": { "alias": "hardcodedDatasource"; "required": false; }; }, {}, never, never, true, never>;
}
//# sourceMappingURL=map-list.component.d.ts.map