import { HttpClient } from '@angular/common/http';
import { MetadatiColonna } from '../class/metadati_colonna';
import { MetaInfo } from '../class/metaInfo';
import { UserInfoService } from './user-info.service';
import { MenuItem } from 'primeng/api';
import { WidgetDefinition } from '../class/widgetDefinition';
import { Dexie, EntityTable } from 'dexie';
import { MetadatiTabella } from '../class/metadati_tabella';
import { MetadatiCustomActionTabella } from '../class/metadati_custom_actions_tabelle';
import { MetadatiUiStiliTabella } from '../class/metadati_ui_stili_tabella';
import { MetadatiUiStiliColonna } from '../class/metadati_ui_stili_colonna';
import { MetadatiUtentiAutorizzazioniColonna } from '../class/metadati_utenti_autorizzazioni_colonna';
import { MetadatiConditionGroup, MetadatiConditionGroupAction } from '../class/metadati_condition_group';
import * as i0 from "@angular/core";
export declare class MetadataProviderService {
    private http;
    private userInfo;
    contentType: string;
    dataType: string;
    type: string;
    getMetadataUri: string;
    getMetadataVersionUri: string;
    static readUri: any;
    static storedUri: any;
    static readUriCmb: any;
    static readDistinctUriCmb: any;
    static updateUri: any;
    static createUri: any;
    static deleteUri: any;
    static restoreUri: any;
    static cloneUri: any;
    static getDistinctValuesUri: any;
    static batchEditUri: any;
    static exportUri: any;
    static exportFromStoredUri: any;
    static exportPdfUri: any;
    static flushCacheUri: any;
    static removeColumnUri: any;
    static checkInstallUri: any;
    static installUri: any;
    static getRealPathUri: any;
    static getMenuByUserIDUri: any;
    static getConnectionsUri: any;
    static getAppSettingsUri: any;
    static updateConnectionsUri: any;
    static deleteConnectionsUri: any;
    static insertConnectionsUri: any;
    static updateAppSettingsUri: any;
    static getLoggedUsersUri: any;
    static GetUserListTestUri: any;
    static readCustomSettingsUri: any;
    static scaffoldODataUri: any;
    static metaTableRoute: any;
    static metaColumnRoute: any;
    static metaMenuRoute: any;
    static metatableActionRoute: any;
    static metatableStyleRoute: any;
    static metatableColumnStyleRoute: any;
    static metatableAuthRoute: any;
    static metatableColumnAuthRoute: any;
    static widgetDefinition: WidgetDefinition;
    static widgetMap: {
        [key: string]: {
            component: any;
            width?: string;
            height?: string;
        };
    };
    static baseLibs: string[];
    static MetaDB: Dexie & {
        MetadatiColonna: EntityTable<MetadatiColonna, "mc_id">;
        MetadatiTabella: EntityTable<MetadatiTabella, "md_id">;
        MetadatiCustomActionTabella: EntityTable<MetadatiCustomActionTabella, "Id">;
        MetadatiUiStiliTabella: EntityTable<MetadatiUiStiliTabella, "must_id">;
        MetadatiUiStiliColonna: EntityTable<MetadatiUiStiliColonna, "musc_id">;
        MetadatiUtentiAutorizzazioniColonna: EntityTable<MetadatiUtentiAutorizzazioniColonna, "muac_id">;
        MetadatiConditionGroup: EntityTable<MetadatiConditionGroup, "CG_Id">;
        MetadatiConditionGroupAction: EntityTable<MetadatiConditionGroupAction, "CAG_Id">;
    };
    static generateLocalDB(version: number): void;
    static getSchemaFromClass(classIntance: any, pKey: string, autoIncrement: boolean, keys?: string[], append?: string): string;
    static isMetaRoute(route: any): boolean;
    static getPKeys(columns: MetadatiColonna[]): MetadatiColonna[];
    static getAggregates(metas: MetadatiColonna[]): any[];
    constructor(http: HttpClient, userInfo: UserInfoService);
    getMetadatiById(md_id: number): Promise<MetadatiColonna[]>;
    getMetadati(route: string, md_id?: number): Promise<MetadatiColonna[]>;
    getMetas(route: string, userId: number, md_id?: number): Promise<any[]>;
    static getResources(): any;
    static translate_meta(metadati: any[], resources: any): void;
    static getTSTypeFromMetaColumn(col: MetadatiColonna): "any" | "boolean" | "string" | "number" | "Date";
    static mapMetadata(metas: MetadatiColonna[]): MetadatiColonna[];
    editMetadataColumn(field: MetadatiColonna): void;
    reorderField(field: MetadatiColonna, upDown: any, metaInfo: MetaInfo): void;
    hideColumn(field: MetadatiColonna, show: boolean, edit: boolean, metaInfo?: MetaInfo): void;
    suggest(field: MetadatiColonna, record: any): void;
    getMenuByUserID(): Promise<MenuItem[]>;
    mapMenu(results: any[], items: MenuItem[], parent?: MenuItem): void;
    scaffoldOdata(): Promise<void>;
    static ɵfac: i0.ɵɵFactoryDeclaration<MetadataProviderService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<MetadataProviderService>;
}
//# sourceMappingURL=metadata-provider.service.d.ts.map