import { AfterViewInit, OnDestroy, OnInit } from '@angular/core';
import { MegaMenuItem, MenuItem } from 'primeng/api';
import { Menubar } from 'primeng/menubar';
import { MetadataProviderService } from '../../service/metadata-provider.service';
import { Observable } from 'rxjs';
import { AuthSessionService, AuthSessionState } from '../../service/auth-session.service';
import { DataSourceComponent } from '../data-source/data-source.component';
import { TranslationManagerService } from '../../service/translation-manager.service';
import { UserInfoService } from '../../service/user-info.service';
import * as i0 from "@angular/core";
export declare class MetaMenuComponent implements OnInit, AfterViewInit, OnDestroy {
    private metaSrv;
    private authSession;
    private trslSrv;
    private userInfo;
    items: MenuItem[];
    megaItems: MegaMenuItem[];
    menu: Menubar;
    menuMetadataDs: DataSourceComponent;
    megaItems2: {
        label: string;
        icon: string;
        items: {
            label: string;
            items: {
                label: string;
            }[];
        }[][];
    }[];
    observer: MutationObserver;
    targetNode: Element;
    config: {
        attributes: boolean;
        childList: boolean;
        subtree: boolean;
    };
    authState$: Observable<AuthSessionState>;
    authReturnUrl: string;
    loginUsername: string;
    loginPassword: string;
    metaMenuRoute: any;
    contextItems: MenuItem[];
    menuAdminMethods: Set<string>;
    draggedMenuId: number | null;
    moveDialogVisible: boolean;
    pendingMove: {
        sourceId: number;
        targetId: number;
        targetLabel?: string;
    } | null;
    dragInProgress: boolean;
    constructor(metaSrv: MetadataProviderService, authSession: AuthSessionService, trslSrv: TranslationManagerService, userInfo: UserInfoService);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onFocus($event: any): void;
    ngOnInit(): Promise<void>;
    onAuthReturnUrlChanged(): void;
    loginWithGoogle(): void;
    logout(): Promise<void>;
    refreshAuthSession(): Promise<void>;
    loginLegacy(): Promise<void>;
    requiresAuthentication(state: AuthSessionState): boolean;
    showAuthBar(state: AuthSessionState): boolean;
    isAdminRole(auth?: any): boolean;
    canOpenMenuContext(auth: AuthSessionState, item: any): boolean;
    canDragMenu(auth: AuthSessionState, item: any): boolean;
    onMenuContext(event: MouseEvent, item: any, auth: AuthSessionState, contextMenu: any): void;
    onMenuDragStart(event: DragEvent, item: any, auth: AuthSessionState): void;
    onMenuDragOver(event: DragEvent, item: any, auth: AuthSessionState): void;
    onMenuDragEnd(): void;
    onMenuDrop(event: DragEvent, item: any, auth: AuthSessionState): Promise<void>;
    private loadMenuIfAllowed;
    private syncMenuAdminMethods;
    hasMenuAdminMethod(methodName: string): boolean;
    private buildContextItems;
    private openMenuMetadata;
    private getNodeContext;
    private isDescendant;
    cancelPendingMove(): void;
    executePendingMove(action: 'before' | 'after' | 'inside'): Promise<void>;
    private setDragState;
    private addMenuEntry;
    private removeMenuEntry;
    private t;
    private tf;
    private ensureMenuObserver;
    static ɵfac: i0.ɵɵFactoryDeclaration<MetaMenuComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MetaMenuComponent, "wuic-meta-menu", never, {}, {}, never, never, true, never>;
}
//# sourceMappingURL=meta-menu.component.d.ts.map