import { AfterViewInit, ChangeDetectorRef, TemplateRef } from '@angular/core';
import { FullCalendarComponent } from '@fullcalendar/angular';
import { CalendarOptions } from '@fullcalendar/core';
import { DataSourceComponent } from '../data-source/data-source.component';
import { MetaInfo } from '../../class/metaInfo';
import { Title } from '@angular/platform-browser';
import { MetadatiColonna } from '../../class/metadati_colonna';
import { DynamicGenericTemplateComponent } from '../dynamic-generic-template/dynamic-generic-template.component';
import { BehaviorSubject } from 'rxjs';
import { TranslationManagerService } from '../../service/translation-manager.service';
import { IBindable } from '../../class/IBindable';
import { IDesigner } from '../../class/IDesigner';
import { SchedulerOptions } from '../../class/schedulerOptions';
import * as i0 from "@angular/core";
export declare class SchedulerListComponent implements AfterViewInit, IBindable, IDesigner<SchedulerOptions> {
    private titleService;
    private cd;
    private trslSrv;
    eventContent: TemplateRef<any>;
    calendar: FullCalendarComponent;
    hardcodedRoute: string;
    parentRecord: any;
    parentMetaInfo: MetaInfo;
    datasource: BehaviorSubject<DataSourceComponent>;
    hardcodedDatasource: DataSourceComponent;
    calendarOptions: CalendarOptions;
    archetypeOptions: SchedulerOptions;
    data: any[];
    private readonly contentRenderers;
    metas: MetadatiColonna[];
    cols: any;
    metaInfo: MetaInfo;
    loading: boolean;
    fromField: string;
    toField: string;
    titleField: string;
    itemTemplateString: string;
    counter: number;
    itemTemplate: typeof DynamicGenericTemplateComponent;
    titleFunction: Function;
    constructor(titleService: Title, cd: ChangeDetectorRef, trslSrv: TranslationManagerService);
    ngAfterViewInit(): void;
    subscribeToDS(): void;
    fix($event: any): void;
    parseData(data: any): any;
    parseDate(date: any, col: MetadatiColonna): Date;
    private updateEvent;
    private refreshCalendarView;
    static ɵfac: i0.ɵɵFactoryDeclaration<SchedulerListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SchedulerListComponent, "wuic-scheduler-list", never, { "hardcodedRoute": { "alias": "hardcodedRoute"; "required": false; }; "parentRecord": { "alias": "parentRecord"; "required": false; }; "parentMetaInfo": { "alias": "parentMetaInfo"; "required": false; }; "datasource": { "alias": "datasource"; "required": false; }; "hardcodedDatasource": { "alias": "hardcodedDatasource"; "required": false; }; }, {}, never, never, true, never>;
}
//# sourceMappingURL=scheduler-list.component.d.ts.map