import { AfterViewInit, ChangeDetectorRef, OnDestroy } from '@angular/core';
import jspreadsheet from "jspreadsheet";
import { MetaInfo } from '../../class/metaInfo';
import { BehaviorSubject } from 'rxjs';
import { DataSourceComponent } from '../data-source/data-source.component';
import { MetadatiColonna } from '../../class/metadati_colonna';
import { Title } from '@angular/platform-browser';
import { ResultInfo } from '../../class/resultInfo';
import { ActivatedRoute } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { UserInfoService } from '../../service/user-info.service';
import * as i0 from "@angular/core";
export declare class SpreadsheetListComponent implements AfterViewInit, OnDestroy {
    private titleService;
    private cd;
    private route;
    private readonly http;
    private readonly userInfoService;
    spreadsheet: any;
    lookupSource: DataSourceComponent;
    hardcodedRoute: string;
    parentRecord: any;
    parentMetaInfo: MetaInfo;
    datasource: BehaviorSubject<DataSourceComponent>;
    hardcodedDatasource: DataSourceComponent;
    spreadsheetOptions: any;
    records: any[];
    metas: MetadatiColonna[];
    currentRoute: BehaviorSubject<string>;
    currentRecord: any;
    currentField: MetadatiColonna;
    cols: any;
    metaInfo: MetaInfo;
    loading: boolean;
    itemTemplateFunction: Function;
    autoCompleteEditor: any;
    inputEvent: any;
    currentEditorInstance: any;
    currentCell: any;
    selectedItem: any;
    info: any;
    autocompleteItems: {
        resultInfo: ResultInfo;
        metaInfo: MetaInfo;
    };
    currentAutocompleteItemIndex: number;
    worksheetInstances: jspreadsheet.worksheetInstance[];
    textCellEditor: any;
    dateCellEditor: any;
    dateTimeCellEditor: any;
    checkboxCellEditor: any;
    pageSize: number;
    pageIndex: number;
    totalRecords: number;
    private themeObserver?;
    private themeRefreshRaf;
    routeName: any;
    private readonly contextMenuHoverClass;
    private readonly contextMenuItemSelector;
    private readonly contextMenuHoverBgFallbackLight;
    private readonly contextMenuHoverBgFallbackDark;
    private readonly contextMenuHoverColorFallbackLight;
    private readonly contextMenuHoverColorFallbackDark;
    private pendingSpreadsheetRows;
    private resolveContextMenuHoverColors;
    private applyContextMenuHoverStyle;
    private clearContextMenuHoverStyle;
    private readonly onContextMenuMouseOver;
    private readonly onContextMenuMouseOut;
    constructor(titleService: Title, cd: ChangeDetectorRef, route: ActivatedRoute, http: HttpClient, userInfoService: UserInfoService);
    ngOnInit(): Promise<void>;
    private createNativeEditor;
    clickItem(clickItemEvent: any): Promise<void>;
    autocomplete(inputEvent: any): Promise<void>;
    debounce(callback: any, waitTime: any): (...args: any[]) => void;
    ngAfterViewInit(): void;
    private subscribeToDS;
    ngOnDestroy(): void;
    private bindContextMenuHoverClass;
    private unbindContextMenuHoverClass;
    private applyAvailableHeight;
    private syncRenderedSpreadsheetHeight;
    private getRenderedBlockHeight;
    onWindowResize(): void;
    private getSpreadsheetTableHeight;
    private canInsertRows;
    private canDeleteRows;
    private isBatchSaveEnabled;
    private markPendingRow;
    private recordMatchesTrackedChange;
    private buildBatchEntity;
    private notifySpreadsheetBatchSave;
    private saveSpreadsheetRecords;
    private getVisibleRowIndexes;
    private handleSpreadsheetInsertRow;
    private handleSpreadsheetDeleteRows;
    private handleSpreadsheetSaveRows;
    private handleSpreadsheetSavePendingChanges;
    private buildSpreadsheetContextMenu;
    initOptions(options: jspreadsheet.Spreadsheet, records: any, metaInfo: any): void;
    getColumn(col: MetadatiColonna): any;
    private getLookupAliasField;
    private createLookupFilterTemplate;
    private applySpreadsheetColumnWidthsFromMetadata;
    private normalizeSpreadsheetColumnWidths;
    private getSpreadsheetRowHeaderWidth;
    private getSpreadsheetMinColumnWidth;
    private getSpreadsheetHeaderFilterIconReserveWidth;
    private parsePercentWidth;
    private parseWeightWidth;
    parseData(data: any, metaInfo: MetaInfo): any[];
    private resolveClientPaginationSize;
    private resolveClientPaginationOptions;
    private resolveServerPaginationSize;
    private resolveServerPaginationOptions;
    private handleServerPageChange;
    private syncPageInfoQueryString;
    private initThemeObserver;
    private scheduleThemeRefresh;
    private enforceSpreadsheetThemeColors;
    private syncServerPaginationSummary;
    private resolvePagerUiColors;
    private applyPagerButtonTheme;
    private resolvePaginationBorderColor;
    private getServerPaginationTokens;
    sortingHandler(direction: any, column: any): (a: any, b: any) => 0 | 1 | -1;
    filter(dateInfoObj?: any): Promise<void>;
    clearFilter(): void;
    test(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SpreadsheetListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SpreadsheetListComponent, "wuic-spreadsheet-list", never, { "hardcodedRoute": { "alias": "hardcodedRoute"; "required": false; }; "parentRecord": { "alias": "parentRecord"; "required": false; }; "parentMetaInfo": { "alias": "parentMetaInfo"; "required": false; }; "datasource": { "alias": "datasource"; "required": false; }; "hardcodedDatasource": { "alias": "hardcodedDatasource"; "required": false; }; }, {}, never, never, true, never>;
}
//# sourceMappingURL=spreadsheet-list.component.d.ts.map