import { BehaviorSubject } from 'rxjs';
import { MetaInfo } from '../../class/metaInfo';
import { DataSourceComponent } from '../data-source/data-source.component';
import { MetadatiColonna } from '../../class/metadati_colonna';
import { Title } from '@angular/platform-browser';
import { DynamicGenericTemplateComponent } from '../dynamic-generic-template/dynamic-generic-template.component';
import { TreeNode } from 'primeng/api';
import { DataProviderService } from '../../service/data-provider.service';
import * as i0 from "@angular/core";
export declare class TreeListComponent {
    private titleService;
    private dataSrv;
    hardcodedRoute: string;
    parentRecord: any;
    parentMetaInfo: MetaInfo;
    datasource: BehaviorSubject<DataSourceComponent>;
    hardcodedDatasource: DataSourceComponent;
    records: any[];
    cols: any[];
    metas: MetadatiColonna[];
    metaInfo: MetaInfo;
    routeName: string;
    totalRecords: number;
    pageSize: number;
    rowNumber: number;
    orderColumn: string;
    orderDir: string;
    loading: boolean;
    pageIndex: number;
    itemTemplateString: string;
    itemTemplate: typeof DynamicGenericTemplateComponent;
    titleFunction: Function;
    initCompleted: boolean;
    treeOptions: any;
    constructor(titleService: Title, dataSrv: DataProviderService);
    ngOnInit(): Promise<void>;
    subscribeToDS(): Promise<void>;
    parseData(data: any): TreeNode<any>[];
    recursiveTreeSearch(node: TreeNode[], key: string): TreeNode<any>;
    onNodeExpand(event: any): Promise<void>;
    static ɵfac: i0.ɵɵFactoryDeclaration<TreeListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TreeListComponent, "wuic-tree-list", never, { "hardcodedRoute": { "alias": "hardcodedRoute"; "required": false; }; "parentRecord": { "alias": "parentRecord"; "required": false; }; "parentMetaInfo": { "alias": "parentMetaInfo"; "required": false; }; "datasource": { "alias": "datasource"; "required": false; }; "hardcodedDatasource": { "alias": "hardcodedDatasource"; "required": false; }; }, {}, never, never, true, never>;
}
//# sourceMappingURL=tree-list.component.d.ts.map