import { AfterViewInit, ElementRef, EventEmitter, Injector, OnDestroy } from '@angular/core';
import { MenuItem } from 'primeng/api';
import { ContextMenu } from 'primeng/contextmenu';
import { DataProviderService } from '../../service/data-provider.service';
import { DataSourceComponent } from '../data-source/data-source.component';
import { MetadataEditorComponent } from '../metadata-editor/metadata-editor.component';
import * as i0 from "@angular/core";
type PaletteNodeDefinition = {
    type: 'start' | 'route' | 'action' | 'condition' | 'end';
    label: string;
    description: string;
};
type WorkflowMenuAuthorization = {
    mmid: number;
    muamid: number;
    muamview: 0 | 1;
    ruoloid: number;
    utenteid: number;
};
type WorkflowStartMenuItem = {
    mm_id: number;
    mm_parent_id: number;
    mm_nome_menu: string;
    mm_display_string_menu: string;
    mm_tooltip_menu: string;
    mm_uri_menu: string;
    mm_ordine: number;
    mm_is_visible_by_default: boolean;
    _Metadati_Utenti_Autorizzazioni_Menus: WorkflowMenuAuthorization[];
};
export declare class WorkflowDesignerComponent implements AfterViewInit, OnDestroy {
    private injector;
    private dataSrv;
    workflowCanvasRef?: ElementRef<HTMLDivElement>;
    primeContextMenu?: ContextMenu;
    routeMetadataDs?: DataSourceComponent;
    startMenuDs?: DataSourceComponent;
    menuAuthDs?: DataSourceComponent;
    routeMetadataEditor?: MetadataEditorComponent;
    actionMetadataEditor?: MetadataEditorComponent;
    workflowChange: EventEmitter<any>;
    readonly paletteNodes: PaletteNodeDefinition[];
    private readonly socket;
    private editor?;
    private area?;
    contextMenuItems: MenuItem[];
    contextMenuNodeId: string | null;
    contextMenuNodeType: string;
    routePopupVisible: boolean;
    routeOptions: Array<{
        label: string;
        value: string;
    }>;
    routeActionOptions: Array<{
        label: string;
        value: string;
    }>;
    selectedRouteName: string;
    selectedRouteAction: string;
    private pendingRouteDrop;
    actionPopupVisible: boolean;
    actionTypeOptions: Array<{
        label: string;
        value: number;
    }>;
    selectedActionTypeId: number | null;
    actionScopeOptions: Array<{
        label: string;
        value: number;
    }>;
    selectedActionScopeId: number | null;
    private pendingActionDrop;
    private readonly actionTypeDictionaryValue;
    routeMetadataDialogVisible: boolean;
    routeMetadataRoute: string;
    workflowKey: string;
    workflowName: string;
    savingWorkflow: boolean;
    loadingWorkflow: boolean;
    savedGraphOptions: Array<{
        label: string;
        value: string;
        name: string;
    }>;
    selectedSavedGraphKey: string;
    loadingSavedGraphs: boolean;
    private routeMetadataNodeId;
    private lastCreatedRouteNodeId;
    private pendingMenuAuthContext;
    private pendingStartMenuContext;
    private localMenuIdSeed;
    private readonly startMenuRoute;
    private readonly menuAuthRoute;
    readonly routeMetadataSaveCallback: Function;
    readonly startMenuSaveCallback: Function;
    readonly menuAuthSaveCallback: Function;
    constructor(injector: Injector, dataSrv: DataProviderService);
    ngAfterViewInit(): Promise<void>;
    ngOnDestroy(): void;
    onPaletteDragStart(event: DragEvent, node: PaletteNodeDefinition): void;
    onCanvasDragOver(event: DragEvent): void;
    onCanvasDrop(event: DragEvent): Promise<void>;
    onCanvasContextMenu(event: MouseEvent): void;
    onCanvasClick(): void;
    deleteContextNode(): Promise<void>;
    openRouteMetadataFromContext(): Promise<void>;
    openActionMetadataFromContext(): Promise<void>;
    get contextStartMenuItems(): WorkflowStartMenuItem[];
    addStartMenuFromContext(): Promise<void>;
    renameStartMenuFromContext(menuInput: WorkflowStartMenuItem | number): Promise<void>;
    private openStartMenuEditor;
    private handleStartMenuSave;
    openInsertMenuAuthorizationFromContext(menuIdRaw: number): Promise<void>;
    openEditMenuAuthorizationFromContext(menuIdRaw: number, muamIdRaw: number): Promise<void>;
    deleteMenuAuthorizationFromContext(menuIdRaw: number, muamIdRaw: number): void;
    getMenuAuthorizationsForContext(menuIdRaw: number): WorkflowMenuAuthorization[];
    getMenuAuthorizationLabel(auth: WorkflowMenuAuthorization): string;
    deleteStartMenuFromContext(menuIdRaw: number): void;
    editStartMenuCaptionFromContext(): void;
    private openMenuAuthorizationEditor;
    private configureMenuAuthorizationEditorMeta;
    private handleMenuAuthorizationSave;
    confirmRouteDrop(): Promise<void>;
    cancelRouteDrop(): void;
    confirmActionDrop(): Promise<void>;
    cancelActionDrop(): void;
    private createNode;
    private addNodeByType;
    private autoConnectRouteToAction;
    private autoConnectStartToRoute;
    private resolveRouteNodeForAutoConnect;
    private emitWorkflow;
    private applyNodeVisualState;
    private normalizeActionNodeVisualContext;
    private inferActionTypeIdFromDescription;
    private computeNodeLabel;
    private getActionTypeVisualLabel;
    private resolveNodeVisual;
    private findNodeHostElement;
    private hideContextMenu;
    private buildContextMenuItems;
    private getNodeIdFromEvent;
    private getNodeIdFromDragEvent;
    private openRoutePopup;
    private openActionPopup;
    private loadRouteOptions;
    private getActionTypeById;
    private getActionScopeById;
    private parseActionTypeOptions;
    private getNodeById;
    private resolveRouteNodeForAction;
    private ensureRouteMetadataBundleForNode;
    private attachActionMetadataToRouteBundle;
    private nextLocalNumericId;
    private maxNumericField;
    private toMetadataSafeName;
    private waitForRouteMetadataEditor;
    private waitForActionMetadataEditor;
    saveWorkflow(): Promise<void>;
    private generateWorkflowKey;
    loadWorkflow(): Promise<void>;
    refreshSavedGraphs(preselectKey?: string): Promise<void>;
    onSavedGraphSelectionChange(): void;
    openSelectedGraph(): Promise<void>;
    renameSelectedGraph(): Promise<void>;
    deleteSelectedGraph(): Promise<void>;
    private serializeGraphPayload;
    private extractRouteMetadataEntries;
    private restoreGraph;
    private findStartNode;
    private ensureInitialStartNode;
    private refreshAllNodeVisualState;
    private rehydrateNodeVisualStateAfterRestore;
    private clearGraph;
    private normalizeLoadedWorkflow;
    private normalizeSavedGraphs;
    private parseMaybeJson;
    private pickFirstDefined;
    private sanitizeForSerialization;
    private nextLocalMenuId;
    private normalizeStartMenuItems;
    private normalizeMenuAuthorizations;
    private nextLocalMenuAuthId;
    private buildRouteMetadataBundle;
    private handleRouteMetadataSave;
    private syncLinkedActionNodesFromMetadataSave;
    private isLinkedActionNode;
    private applyLinkedActionTypeToNode;
    private removeInvalidOutgoingConnections;
    private normalizeEditFormRecord;
    private unwrapEditorFieldValue;
    private createEmptyRouteBundle;
    private applyRecordToBundle;
    private nextLocalBundleItemId;
    private upsertById;
    private rebuildDerivedRouteCollections;
    private applyRouteMetadataBundleToDatasource;
    private t;
    private tf;
    static ɵfac: i0.ɵɵFactoryDeclaration<WorkflowDesignerComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<WorkflowDesignerComponent, "wuic-workflow-designer", never, {}, { "workflowChange": "workflowChange"; }, never, never, true, never>;
}
export {};
//# sourceMappingURL=workflow-designer.component.d.ts.map