// Per-route render strategy used by the prerender pipeline. Angular 21
// requires explicit handling for any route that includes a parameter
// (`:slug`, `:id`, …) because the prerender extractor doesn't know which
// concrete URLs to materialize. Without this file the build fails:
//   "The 'X/:slug' route uses prerendering and includes parameters, but
//    'getPrerenderParams' is missing."
//
// Strategy:
//   - `/docs/:slug` and `/blog/:slug`:  RenderMode.Client. The page still
//     loads (SPA fallback), but no `<route>/index.html` is shipped. SEO
//     impact is acceptable because:
//       • /blog is a Sprint-1 placeholder (noindex), so its children
//         shouldn't be in the index either.
//       • /docs/:slug content is loaded dynamically from the docs manifest
//         at runtime — even if we prerendered, the body text would be
//         empty until the manifest fetch completes.
//   - everything else falls through to the catch-all `**` rule which
//     keeps the build's overall `prerender: true` behavior — the same
//     `prerender-routes.txt` list is what actually gets prerendered.
//
// When /docs/:slug graduates to per-slug prerender (Sprint 6 or later),
// switch its entry to `RenderMode.Prerender` + `getPrerenderParams` that
// returns the slug list from docs.generated.json.
import { RenderMode, ServerRoute } from '@angular/ssr';

/**
 * Read the blog manifest at prerender time and return one slug entry per
 * post. The manifest is generated by scripts/generate-blog-manifest.mjs
 * during the prebuild step, so by the time the prerender extractor runs
 * the file is already in `public/blog-manifest.json`.
 *
 * Reading via dynamic Node `fs` import keeps this file safe to compile
 * for the browser bundle too — the function only ever runs server-side
 * during prerender. If the manifest is missing or empty (no posts) we
 * return an empty array → no /blog/:slug pages are prerendered, which is
 * the right behavior (the SPA fallback handles the route).
 */
async function blogPrerenderSlugs(): Promise<{ slug: string }[]> {
  try {
    const fs = await import('node:fs');
    const path = await import('node:path');
    const manifestPath = path.resolve(process.cwd(), 'public/blog-manifest.json');
    if (!fs.existsSync(manifestPath)) return [];
    const raw = fs.readFileSync(manifestPath, 'utf8');
    const manifest = JSON.parse(raw) as { posts: { slug: string }[] };
    return (manifest.posts ?? []).map(p => ({ slug: p.slug }));
  } catch {
    return [];
  }
}

export const serverRoutes: ServerRoute[] = [
  { path: 'docs/:slug', renderMode: RenderMode.Client },
  // Blog posts: prerender each slug discovered in the manifest. With
  // soft-launch noindex still on the page, prerendering doesn't make the
  // article indexable — but it gives reviewers a fast first-byte and
  // means the title/description/JSON-LD are present in the static HTML
  // when sharing draft links internally (Slack/email previews).
  {
    path: 'blog/:slug',
    renderMode: RenderMode.Prerender,
    getPrerenderParams: blogPrerenderSlugs,
  },
  { path: '**', renderMode: RenderMode.Prerender },
];
