// Per-route render strategy used by the prerender pipeline. Angular 21
// requires explicit handling for any route that includes a parameter
// (`:slug`, `:id`, …) because the prerender extractor doesn't know which
// concrete URLs to materialize. Without this file the build fails:
//   "The 'X/:slug' route uses prerendering and includes parameters, but
//    'getPrerenderParams' is missing."
//
// Strategy:
//   - `/docs/:slug` and `/blog/:slug`:  RenderMode.Client. The page still
//     loads (SPA fallback), but no `<route>/index.html` is shipped. SEO
//     impact is acceptable because:
//       • /blog is a Sprint-1 placeholder (noindex), so its children
//         shouldn't be in the index either.
//       • /docs/:slug content is loaded dynamically from the docs manifest
//         at runtime — even if we prerendered, the body text would be
//         empty until the manifest fetch completes.
//   - everything else falls through to the catch-all `**` rule which
//     keeps the build's overall `prerender: true` behavior — the same
//     `prerender-routes.txt` list is what actually gets prerendered.
//
// When /docs/:slug graduates to per-slug prerender (Sprint 6 or later),
// switch its entry to `RenderMode.Prerender` + `getPrerenderParams` that
// returns the slug list from docs.generated.json.
import { RenderMode, ServerRoute } from '@angular/ssr';

/**
 * Read the blog manifest at prerender time and return one slug entry per
 * post. The manifest is generated by scripts/generate-blog-manifest.mjs
 * during the prebuild step, so by the time the prerender extractor runs
 * the file is already in `public/blog-manifest.json`.
 *
 * Reading via dynamic Node `fs` import keeps this file safe to compile
 * for the browser bundle too — the function only ever runs server-side
 * during prerender. If the manifest is missing or empty (no posts) we
 * return an empty array → no /blog/:slug pages are prerendered, which is
 * the right behavior (the SPA fallback handles the route).
 */
async function blogPrerenderSlugs(): Promise<{ slug: string }[]> {
  try {
    const fs = await import('node:fs');
    const path = await import('node:path');
    const manifestPath = path.resolve(process.cwd(), 'public/blog-manifest.json');
    if (!fs.existsSync(manifestPath)) return [];
    const raw = fs.readFileSync(manifestPath, 'utf8');
    const manifest = JSON.parse(raw) as { posts: { slug: string }[] };
    return (manifest.posts ?? []).map(p => ({ slug: p.slug }));
  } catch {
    return [];
  }
}

/**
 * Prefissi locale (allineati a services/locale-url.ts — duplicati come
 * literal per non importare codice browser in questo file server-only).
 * Le route parametriche esistono anche sotto ogni prefisso (/it/docs/:slug,
 * /fr/blog/:slug, ...) e ognuna richiede la sua entry esplicita: il matching
 * delle ServerRoute è sul path COMPLETO.
 */
const LOCALE_PREFIXES = ['it', 'fr', 'es', 'de'] as const;

/**
 * Prefissi per cui le pagine `/docs/:slug` vengono prerenderizzate (oltre
 * alla root EN, sempre inclusa). Volutamente un SOTTOINSIEME: 79 slug × 5
 * lingue sono 395 pagine, e oggi non esiste un solo dato su quanto rendano —
 * non lo sono mai state, perché emettevano tutte `canonical=/docs`. Partiamo
 * da EN+IT (i due mercati con campagne attive), si misura in Search Console,
 * e per estendere a fr/es/de basta aggiungerli qui e in generate-sitemap.mjs
 * (DOCS_SITEMAP_PREFIXES) — le due liste vanno tenute allineate.
 */
const DOCS_PRERENDER_PREFIXES = ['it'] as const;

/**
 * Slug delle pagine docs, letti da `public/docs-index.json` — l'indice leggero
 * (~1,5 KB) che il generatore emette accanto ai manifesti per lingua. Qui
 * servono i soli slug: leggerli da un manifesto di contenuto significherebbe
 * parsare centinaia di KB per ricavarne un elenco di stringhe.
 */
async function docsPrerenderSlugs(): Promise<{ slug: string }[]> {
  try {
    const fs = await import('node:fs');
    const path = await import('node:path');
    const indexPath = path.resolve(process.cwd(), 'public/docs-index.json');
    if (!fs.existsSync(indexPath)) return [];
    const raw = fs.readFileSync(indexPath, 'utf8');
    const index = JSON.parse(raw) as { slugs: string[] };
    return (index.slugs ?? []).map(slug => ({ slug }));
  } catch {
    return [];
  }
}

export const serverRoutes: ServerRoute[] = [
  // Docs: prerender per-slug su EN (root) e IT — vedi DOCS_PRERENDER_PREFIXES.
  {
    path: 'docs/:slug',
    renderMode: RenderMode.Prerender,
    getPrerenderParams: docsPrerenderSlugs,
  },
  ...DOCS_PRERENDER_PREFIXES.map(p => ({
    path: `${p}/docs/:slug`,
    renderMode: RenderMode.Prerender,
    getPrerenderParams: docsPrerenderSlugs,
  } as ServerRoute)),
  // Lingue non ancora prerenderizzate: restano client-rendered e FUORI
  // sitemap. Le pagine esistono e sono raggiungibili, semplicemente non le
  // spingiamo al crawl finché EN/IT non dimostrano di raccogliere impression.
  ...LOCALE_PREFIXES
    .filter(p => !DOCS_PRERENDER_PREFIXES.includes(p as typeof DOCS_PRERENDER_PREFIXES[number]))
    .map(p => ({ path: `${p}/docs/:slug`, renderMode: RenderMode.Client } as ServerRoute)),
  // Blog posts: prerender each slug discovered in the manifest — dal fix
  // HttpClient (2026-07-14) l'HTML statico contiene il BODY dell'articolo,
  // non più "Loading article…".
  {
    path: 'blog/:slug',
    renderMode: RenderMode.Prerender,
    getPrerenderParams: blogPrerenderSlugs,
  },
  // Varianti locale del blog: prerender anche loro (chrome tradotto, stesso
  // body single-language). Canonical/hreflang le puntano alla root (vedi
  // blog-post.ts localizedUrls:false) → nessun rischio duplicati in SERP.
  ...LOCALE_PREFIXES.map(p => ({
    path: `${p}/blog/:slug`,
    renderMode: RenderMode.Prerender,
    getPrerenderParams: blogPrerenderSlugs,
  } as ServerRoute)),
  // Tutte le route statiche — INCLUSI gli alberi /it /fr /es /de (l'extractor
  // scopre i figli statici dei wrapper locale e li prerenderizza ×5).
  { path: '**', renderMode: RenderMode.Prerender },
];
